version: '3'
services:
  primary:
    image: mcr.microsoft.com/azurelinux/base/core:3.0
    command: >
      sh -c "
        timeout 30 sh -c 'until curl -s http://localhost:8080/status > /dev/null 2>&1; do sleep 1; done'
        curl "http://localhost:8080/attest/maa" \
          -s \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "maa_endpoint": "cacidashboard.weu.attest.azure.net",
            "runtime_data": "'$(echo '{
              "keys": [
                {
                  "key_ops": ["encrypt"],
                  "kid": "example-key",
                  "kty": "oct-HSM",
                  "k": "example"
                }
              ]
            }' | base64 -w 0)'"
          }'
      "
  attestation:
    image: mcr.microsoft.com/aci/skr:$TAG
