version: '3'
services:
  workload:
    image: cacidashboard.azurecr.io/${REPO_BASE:-stress_tests}/workload:${TAG:-latest}
    build:
      context: .
      dockerfile: workload.Dockerfile
  sidecar:
    image: cacidashboard.azurecr.io/${REPO_BASE:-stress_tests}/sidecar:${TAG:-latest}
    build:
      context: .
      dockerfile: sidecar.Dockerfile
