.create table CACITestStepTrace (
    UniqueRunId: guid,
    Timestamp: datetime,
    ResourceGroup: string,
    DeploymentName: string,
    Branch: string,
    Location: string,
    AvailabilityZone: string,
    TestType: string,
    TestName: string,
    TestSchedule: string,
    RunFeatures: dynamic,
    RunLink: string,
    StepName: string,
    Status: string,
    Error: string,
    Output: dynamic
) with (folder = "C-ACI")

.create-or-alter function with (folder = "C-ACI") getCACITestSummary(startTime:datetime,endTime:datetime) {
    CACITestStepTrace
    | where Timestamp between (startTime .. endTime)
    | sort by Timestamp asc
    | summarize
        ResourceGroup=take_any(ResourceGroup),
        DeploymentName=take_any(DeploymentName),
        Branch=take_any(Branch),
        Location=take_any(Location),
        AvailabilityZone=take_any(AvailabilityZone),
        TestType=take_any(TestType),
        TestName=take_any(TestName),
        TestSchedule=take_any(TestSchedule),
        RunFeatures=take_any(RunFeatures),
        RunLink=take_any(RunLink),
        StartTime=min(Timestamp),
        EndTime=max(Timestamp),
        Duration=max(Timestamp)-min(Timestamp),
        Failed=take_anyif(True, Error != ''),
        Error=strcat_array(make_list_if(strcat(StepName, ": ", Error), Error != ''), '\n'),
        StepOutputs=make_bag_if(bag_pack(StepName, Output), isnotnull(Output)),
        _LastStep=arg_max(Timestamp, StepName)[1],
        _LastStepStatus=arg_max(Timestamp, Status)[1]
        by UniqueRunId
    | extend Failed=iff(isempty(Failed),False,Failed), LastRunningStep=iff(_LastStepStatus == "Started", _LastStep, "")
    | project-away _LastStep, _LastStepStatus
    | sort by StartTime desc
}

.create table CACIMAATestTrace (
    Time: datetime,
    RandomId: guid,
    Environment: string,
    Region: string,
    ClientRegion: string,
    MAAEndpoint: string,
    TEE: string,
    Error: string,
    Logs: string
)

.create-or-alter function with (folder = "C-ACI") CACIMonitoringIcMTriggers() {
    let failureLookbackHours=3;
    let showRunsLookbackHours=6;
    let errorCountThreshold=8;
    let regions = dynamic([
        'australiacentral',
        // 'australiacentral2',
        'australiaeast',
        'austriaeast',
        'brazilsouth',
        'brazilsoutheast',
        'centralindia',
        'centralus',
        'centraluseuap',
        'chilecentral',
        'eastasia',
        'eastus',
        'eastus2',
        // 'eastus2euap',
        'francecentral',
        'germanynorth',
        'germanywestcentral',
        'indonesiacentral',
        'israelcentral',
        'italynorth',
        'japaneast',
        'japanwest',
        'koreacentral',
        'koreasouth',
        'newzealandnorth',
        'northeurope',
        'norwayeast',
        'polandcentral',
        'southafricanorth',
        'southcentralus',
        'southeastasia',
        'southindia',
        'swedencentral',
        'switzerlandnorth',
        'taiwannorth',
        'uaenorth',
        'uksouth',
        'westeurope',
        'westus',
        'westus2',
        'westus3'
    ]);
    let branch = "main";
    // let testData = datatable (Location: string, AvailabilityZone: string, TestVariant: string, StartTime: datetime, DeploymentName: string, RunLink: string, Error: string) [
    //     "australiacentral2", "2", "fake zonal test", "2025-08-07 11:00:00", "test1", "https://github.com", "!",
    //     "australiacentral2", "3", "fake zonal test", "2025-08-07 12:01:00", "test2", "https://github.com", "!!",
    //     "westeurope", "", "fake non-zonal test", "2025-08-07 13:02:00", "test3", "https://github.com", "!!!",
    // ];
    let currentTime=now();
    let mainData=(
        getCACITestSummary(currentTime-make_timespan(showRunsLookbackHours, 0), currentTime)
        | where Location in (regions) and Branch == branch and TestType == "aci" and TestSchedule == "gh-hourly"
        | project
            Location,
            AvailabilityZone,
            TestVariant=case(
                array_length(RunFeatures) == 0,
                    iff(TestName contains "attestation", "MAA attestation from fresh ACI", "non-vnet test"),
                array_index_of(RunFeatures, "vnet") >= 0, "vnet test",
                "(unknown)"
            ),
            StartTime,
            DeploymentName,
            RunLink,
            Error
        | extend ErrorJson=parse_json(extract("\\nERROR: (\\{.+\\})\\n", 1, Error))
        | extend ErrDetail=coalesce(ErrorJson["error"]["details"][0], ErrorJson["error"])
        | extend Error=coalesce(iff(isnotempty(ErrDetail), strcat(tostring(ErrDetail["code"]), ": ", strcat(tostring(ErrDetail["message"]), "\n", tostring(ErrDetail['details']))), dynamic(null)), Error)
    );
    let maaData=(
        CACIMAATestTrace
        | where Region in (regions) and Time between (currentTime-make_timespan(showRunsLookbackHours, 0) .. currentTime)
        | project
            Location=Region,
            AvailabilityZone='',
            TestVariant='MAA attestation from long-lived ACI',
            StartTime=Time,
            DeploymentName=strcat('MAA tester from ', ClientRegion, ' testing ', MAAEndpoint, ' (', Region, ', TEE ', TEE, ')'),
            RunLink=strcat('https://dataexplorer.azure.com/dashboards/d244d12c-7f39-475f-9f17-1f28a0848b9e?p-_randomID=v-', RandomId, '#228f4b7c-9b3f-4a2e-a3c6-513ec518c897'),
            Error=Error
    );
    union mainData, maaData //, testData
    // | union testData
    | order by StartTime desc
    | extend CountAsError=isnotempty(Error) and StartTime >= currentTime-make_timespan(failureLookbackHours, 0)
    | summarize
        Tests=make_list(bag_pack_columns(Location, AvailabilityZone, StartTime, DeploymentName, RunLink, Error)),
        ErrorCountInLookbackTimeRange=countif(CountAsError),
        FaultyZones=make_set_if(iff(isnotempty(AvailabilityZone), strcat("zone ", AvailabilityZone), "(no zone)"), CountAsError)
        by Location, TestVariant
    | order by ErrorCountInLookbackTimeRange desc
    | summarize
        Variants=make_list(bag_pack("TestVariant", TestVariant, "Tests", Tests)),
        ErrorCountInLookbackTimeRange=sum(ErrorCountInLookbackTimeRange),
        FaultyZones=make_set(FaultyZones),
        FaultyTests=make_set_if(TestVariant, ErrorCountInLookbackTimeRange > 0)
        by Location
    | order by Location asc
    | extend
        FaultyZones=array_sort_asc(FaultyZones),
        FaultyTests=array_sort_asc(FaultyTests)
    | extend
        IcmTitle=iff(
            ErrorCountInLookbackTimeRange >= errorCountThreshold,
            strcat(
                "[C-ACI E2E Monitor] ", strcat_array(FaultyTests, ", "),
                " in region ", Location,
                " has failed total ", ErrorCountInLookbackTimeRange,
                " times in ", strcat_array(FaultyZones, ", "),
                " over the last ", failureLookbackHours, " hours"
            ),
            ""
        ),
        IcmCorrelationName=strcat("c-aci-dashboard-", Location)
}
