version: '3'
services:
  workload:
    image: ${REGISTRY:-cacidashboard.azurecr.io}/${REPO_BASE:-stress_tests_noserver}/workload:${TAG:-latest}
    build:
      context: .
      dockerfile: workload.Dockerfile
  sidecar:
    image: ${REGISTRY:-cacidashboard.azurecr.io}/${REPO_BASE:-stress_tests_noserver}/sidecar:${TAG:-latest}
    build:
      context: .
      dockerfile: sidecar.Dockerfile
