name: Attestation - New Zealand North

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/attestation-newzealandnorth.yml
  schedule:
    - cron: '23 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  attestation-newzealandnorth:
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      location: newzealandnorth
      policy_type: allow_all
      test_schedule: gh-hourly
