name: Attestation - Germany North

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/attestation-germanynorth.yml
  schedule:
    - cron: '19 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  attestation-germanynorth:
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      location: germanynorth
      policy_type: allow_all
      test_schedule: gh-hourly
