name: Attestation - East US

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/attestation-eastus.yml
  schedule:
    - cron: '13 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  attestation-eastus:
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      location: eastus
      policy_type: allow_all
      test_schedule: gh-hourly
