name: Attestation - East US 2

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '14 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  attestation-eastus2:
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      location: eastus2
      policy_type: allow_all
      test_schedule: gh-hourly
