name: Attestation - UAE North

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/attestation-uaenorth.yml
  schedule:
    - cron: '30 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  attestation-uaenorth:
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      location: uaenorth
      policy_type: allow_all
      test_schedule: gh-hourly
