name: Region (Basic) - South East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/basic-region-southeastasia.yml

jobs:
  basic-southeastasia:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: southeastasia
