name: Region (Basic) - West US 2

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '30 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-westus2:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: westus2
