name: Region (Basic) - West US 3

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '11,26,41,56 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-westus3:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: westus3
