name: Region (Basic) - Germany West Central

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/basic-region-germanywestcentral.yml
  schedule:
    - cron: '19 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-germanywestcentral:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: germanywestcentral

  # Only zones 1 and 2 exist in germanywestcentral. Note that this will change
  # when we run in a different subscription.
  info-two-zones:
    if: ${{ !cancelled() }}
    name: info-two-zones
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        # only vnets are supported for zonal deployments
        use_vnet: [true]
        zone: ["1", "2"]
    with:
      id: info-two-zones${{ matrix.zone }}-${{ matrix.use_vnet && 'vnet-' || '' }}allow_all
      location: germanywestcentral
      use_vnet: ${{ matrix.use_vnet }}
      zone: ${{ matrix.zone }}
      policy_type: allow_all
      test_schedule: gh-hourly
