name: Region (Basic) - Israel Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/basic-region-israelcentral.yml

jobs:
  basic-israelcentral:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: israelcentral
