name: Region (Basic) - Germany West Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '12 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-germanywestcentral:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: germanywestcentral
