name: Region (Basic) - Italy North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '11,26,41,56 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-italynorth:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: italynorth
