name: Region (Basic) - Israel Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '10,25,40,55 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-israelcentral:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: israelcentral
