name: Region (Basic) - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '10 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-eastus2euap:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: eastus2euap
