name: Region (Basic) - West US 2

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '20 3 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/basic-region-westus2.yml

jobs:
  basic-westus2:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: westus2
