name: Region (Basic) - Switzerland North

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/basic-region-switzerlandnorth.yml
  schedule:
    - cron: '25 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-switzerlandnorth:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: switzerlandnorth
