name: Region (Basic)

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/basic-region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'
  workflow_dispatch:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:
  info-nonzoned-nonvnet:
    if: ${{ !cancelled() && !contains(vars.ACI_VNET_ONLY_REGIONS, format(',{0},', inputs.location)) && !contains(vars.ACI_ONLY_ZONAL_VNET_REGIONS, format(',{0},', inputs.location)) }}
    name: info-nonzoned-nonvnet
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    with:
      id: info-allow_all
      location: ${{ inputs.location }}
      use_vnet: false
      policy_type: allow_all
      test_schedule: gh-hourly

  info-nonzoned-vnet:
    if: ${{ !cancelled() && !contains(vars.ACI_ONLY_ZONAL_VNET_REGIONS, format(',{0},', inputs.location)) }}
    name: info-nonzoned-vnet
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    with:
      id: info-vnet-allow_all
      location: ${{ inputs.location }}
      use_vnet: true
      policy_type: allow_all
      test_schedule: gh-hourly

  info-zoned-1-2:
    if: ${{ !cancelled() && contains(vars.ACI_ZONE_1_2_REGIONS, format(',{0},', inputs.location)) }}
    name: info-zoned
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        # only vnets are supported for zonal deployments
        use_vnet: [true]
        zone: ["1", "2"]
    with:
      id: info-zone${{ matrix.zone }}-${{ matrix.use_vnet && 'vnet-' || '' }}allow_all
      location: ${{ inputs.location }}
      use_vnet: ${{ matrix.use_vnet }}
      zone: ${{ matrix.zone }}
      policy_type: allow_all
      test_schedule: gh-hourly

  info-zoned:
    if: ${{ !cancelled() && contains(vars.ACI_ZONED_REGIONS, format(',{0},', inputs.location)) }}
    name: info-zoned
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        # only vnets are supported for zonal deployments
        use_vnet: [true]
        zone: ["1", "2", "3"]
    with:
      id: info-zone${{ matrix.zone }}-${{ matrix.use_vnet && 'vnet-' || '' }}allow_all
      location: ${{ inputs.location }}
      use_vnet: ${{ matrix.use_vnet }}
      zone: ${{ matrix.zone }}
      policy_type: allow_all
      test_schedule: gh-hourly
