name: Region (Basic) - South East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '4,19,34,49 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-southeastasia:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: southeastasia
