name: Region (Basic) - Korea Central

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/basic-region-koreacentral.yml
  schedule:
    - cron: '22 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-koreacentral:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: koreacentral
