name: Region (Basic) - Japan West

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/basic-region-japanwest.yml
  schedule:
    - cron: '21 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-japanwest:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: japanwest
