name: Region (Basic) - Sweden Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '24 1-23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  basic-swedencentral:
    secrets: inherit
    uses: ./.github/workflows/basic-region.yml
    with:
      location: swedencentral
