name: Region (Basic)

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/basic-region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'
  workflow_dispatch:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:
  info-nonzoned-nonvnet:
    # don't do non-vnet for australiacentral2 for now
    if: ${{ !cancelled() && inputs.location != 'australiacentral2' }}
    name: info-nonzoned-nonvnet
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    with:
      id: info-allow_all
      location: ${{ inputs.location }}
      use_vnet: false
      policy_type: allow_all
      test_schedule: gh-hourly

  info-nonzoned-vnet:
    if: ${{ !cancelled() }}
    name: info-nonzoned-vnet
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    with:
      id: info-vnet-allow_all
      location: ${{ inputs.location }}
      use_vnet: true
      policy_type: allow_all
      test_schedule: gh-hourly

  info-zoned:
    if: ${{ !cancelled() && contains(vars.ACI_ZONED_REGIONS, format(',{0},', inputs.location)) }}
    name: info-zoned
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        # only vnets are supported for zonal deployments
        use_vnet: [true]
        zone: ["1", "2", "3"]
    with:
      id: info-zone${{ matrix.zone }}-${{ matrix.use_vnet && 'vnet-' || '' }}allow_all
      location: ${{ inputs.location }}
      use_vnet: ${{ matrix.use_vnet }}
      zone: ${{ matrix.zone }}
      policy_type: allow_all
      test_schedule: gh-hourly

  # Only zones 2 and 3 exist in east us 2 euap. Note that this will change
  # when we run in a different subscription.
  info-two-zones:
    if: ${{ !cancelled() && inputs.location == 'eastus2euap' }}
    name: info-two-zones
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        # only vnets are supported for zonal deployments
        use_vnet: [true]
        zone: ["1", "3"]
    with:
      id: info-two-zones${{ matrix.zone }}-${{ matrix.use_vnet && 'vnet-' || '' }}allow_all
      location: ${{ inputs.location }}
      use_vnet: ${{ matrix.use_vnet }}
      zone: ${{ matrix.zone }}
      policy_type: allow_all
      test_schedule: gh-hourly
