name: Build and push test containers

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}/test-containers

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Use short date as tag
        run: |
          TAG=$(date "+%Y%m%d")
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push containers
        run: cd containers && make REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY TAG=$TAG push

      - name: Tag with latest
        if: github.ref == 'refs/heads/main'
        run: |
          # Rebuilding the image won't change it due to caching
          cd containers && make REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY TAG=latest push
