name: Build and push test containers (arm64)

on:
  pull_request:
    paths:
      - .github/workflows/build-test-containers-arm.yaml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  DOCKER_BUILDKIT: 1
  REGISTRY: cacidashboardaci.azurecr.io
  REPOSITORY: prebuilt-test-containers
  IMAGE_PLATFORM: linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ACI }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ env.REGISTRY }}

      - name: Use short date as tag
        run: |
          TAG=$(date "+%Y%m%d")
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push containers (linux/arm64)
        run: cd containers && make REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY TAG=$TAG IMAGE_PLATFORM=$IMAGE_PLATFORM push

      - name: Tag with latest
        if: github.ref == 'refs/heads/main'
        run: |
          # Rebuilding the image won't change it due to caching
          cd containers && make REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY TAG=latest IMAGE_PLATFORM=$IMAGE_PLATFORM push
