name: Cleanup

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-container-groups:
    name: Cleanup Container Groups
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Cleanup Container Groups
        run: |
          RUNNING_CONTAINERS=$(az container list \
          --resource-group c-aci-dashboard \
          --query "[?!starts_with(name, 'uptime-')]")

          for container in $(echo $RUNNING_CONTAINERS | jq -r '.[].id'); do
              echo "Deleting container group: ${container}"
              az resource delete --ids ${container}
          done

  cleanup-vms:
    name: Cleanup Virtual Machines
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Cleanup VMs
        run: |
          RUNNING_VMS=$(az vm list --resource-group c-aci-dashboard --query '[].id' -o tsv)
          for vm in $RUNNING_VMS; do
              echo "Deleting VM: ${vm}"
              az vm delete --ids ${vm} --yes --force-deletion yes --verbose
              vm_deployment_name=`echo $vm | grep -oP '(?<=/virtualMachines/).*(?=-vm)'`
              echo "Deleting vnet and nsg: ${vm_deployment_name}-..."
              az resource delete --resource-group c-aci-dashboard -n ${vm_deployment_name}-vnet --resource-type Microsoft.Network/virtualNetworks --verbose
              az resource delete --resource-group c-aci-dashboard -n ${vm_deployment_name}-nsg --resource-type Microsoft.Network/networkSecurityGroups --verbose
          done

  cleanup-images:
    name: Cleanup Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Cleanup pushed images
        run: |
          az acr run --registry cacidashboard --cmd 'acr purge --filter "^stress_tests/.+:.*" --ago 0d --keep 1 --untagged' /dev/null
          az acr run --registry cacidashboard --cmd 'acr purge --filter "^stress_tests_noserver/.+:.*" --ago 0d --keep 1 --untagged' /dev/null
          az acr run --registry cacidashboard --cmd 'acr purge --filter "^workload-sidecar-with-fragments/.+:.*" --ago 0d --keep 1 --untagged' /dev/null

  cleanup-nics:
    name: Cleanup Network Interfaces
    runs-on: ubuntu-latest
    needs: cleanup-vms
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Cleanup NICs
        run: |
          for NIC in $(az network nic list -g c-aci-dashboard --query "[].name" -o tsv); do
              az network nic delete --no-wait -g c-aci-dashboard -n $NIC || true
          done

  cleanup-vnets:
    name: Cleanup Virtual Networks
    # Both container groups and VMs might be in a vnet, and we can't delete the vnet until they're gone
    needs: ['cleanup-container-groups', 'cleanup-nics']
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Cleanup VNETs
        run: |
          for VNET in $(az network vnet list -g c-aci-dashboard --query "[].name" -o tsv); do
              az network vnet delete --no-wait -g c-aci-dashboard -n $VNET || true
          done

  cleanup-nsgs:
    name: Cleanup Network Security Groups
    runs-on: ubuntu-latest
    needs: cleanup-vnets
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Cleanup NSGs
        run: |
          for NSG in $(az network nsg list -g c-aci-dashboard --query "[].name" -o tsv); do
              az network nsg delete --no-wait -g c-aci-dashboard -n $NSG || true
          done

  cleanup-deployments:
    name: Cleanup ARM Deployments
    runs-on: ubuntu-latest
    needs: ['cleanup-container-groups', 'cleanup-vms']
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Cleanup ARM Deployments
        run: |
          for deployment in $(az deployment group list -g c-aci-dashboard --query "[].name" -o tsv); do
              echo "Deleting deployment: ${deployment}"
              az deployment group delete --name $deployment -g c-aci-dashboard
          done
