name: High Spec - UAE North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '54 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-uaenorth:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: uaenorth
