name: High Spec - Switzerland North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '53 6 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-switzerlandnorth:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: switzerlandnorth
