name: High Spec - East US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '38 6 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-eastus:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: eastus
