name: High Spec - France South

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '55 22 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-francesouth:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: francesouth
