name: High Spec - West Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '47 23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-westeurope:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: westeurope
