name: High Spec - Italy North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '20 21 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-italynorth:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: italynorth
