name: High Spec

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/high-spec.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/high-spec.yml
  workflow_dispatch:
    inputs:
      location:
        type: string
        description: Test region
        required: true
  workflow_call:
    inputs:
      location:
        type: string
        description: Test region
        required: true

jobs:
  stress-4cpu-16gb:
    secrets: inherit
    # This should be available in all regions
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 4cpu-16gb
      location: ${{ inputs.location }}
      cpu: 4
      memory_in_gb: 16
      cleanup: "always"
      is_big_containers_test: false

  stress-8cpu-16gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && (contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) || contains(vars.ACI_BIG_CONTAINERS_REGION_8CPU_ONLY, format(',{0},', inputs.location))) }}
    # Serializes execution
    needs: stress-4cpu-16gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 8cpu-16gb
      location: ${{ inputs.location }}
      cpu: 8
      memory_in_gb: 16
      cleanup: "always"
      is_big_containers_test: true

  managed-identity-8cpu-16gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && (contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) || contains(vars.ACI_BIG_CONTAINERS_REGION_8CPU_ONLY, format(',{0},', inputs.location))) }}
    # Serializes execution
    needs: stress-8cpu-16gb
    uses: ./.github/workflows/workload-managed-identity.yml
    with:
      id: msi-8cpu-16gb
      location: ${{ inputs.location }}
      cpu: 8
      memory_in_gb: 16
      cleanup: "always"
      is_big_containers_test: true

  stress-16cpu-32gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: managed-identity-8cpu-16gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 16cpu-32gb
      location: ${{ inputs.location }}
      cpu: 16
      memory_in_gb: 32
      cleanup: "always"
      is_big_containers_test: true

  stress-17cpu-32gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-16cpu-32gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 17cpu-32gb
      location: ${{ inputs.location }}
      cpu: 17
      memory_in_gb: 32
      cleanup: "always"
      is_big_containers_test: true

  stress-18cpu-32gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-17cpu-32gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 18cpu-32gb
      location: ${{ inputs.location }}
      cpu: 18
      memory_in_gb: 32
      cleanup: "always"
      is_big_containers_test: true

  stress-20cpu-32gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-18cpu-32gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 20cpu-32gb
      location: ${{ inputs.location }}
      cpu: 20
      memory_in_gb: 32
      cleanup: "always"
      is_big_containers_test: true

  stress-24cpu-32gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-20cpu-32gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 24cpu-32gb
      location: ${{ inputs.location }}
      cpu: 24
      memory_in_gb: 32
      cleanup: "always"
      is_big_containers_test: true

  # stress-28cpu-32gb:
  #   secrets: inherit
  #   # BigContainers regions
  #   if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
  #   # Serializes execution
  #   needs: stress-24cpu-32gb
  #   uses: ./.github/workflows/workload-stress-tests.yml
  #   with:
  #     id: 28cpu-32gb
  #     location: ${{ inputs.location }}
  #     cpu: 28
  #     memory_in_gb: 32
  #     cleanup: "always"
  #     is_big_containers_test: true

  stress-18cpu-64gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-24cpu-32gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 18cpu-64gb
      location: ${{ inputs.location }}
      cpu: 18
      memory_in_gb: 64
      cleanup: "always"
      is_big_containers_test: true

  stress-18cpu-96gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-18cpu-64gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 18cpu-96gb
      location: ${{ inputs.location }}
      cpu: 18
      memory_in_gb: 96
      cleanup: "always"
      is_big_containers_test: true

  stress-18cpu-112gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-18cpu-96gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 18cpu-112gb
      location: ${{ inputs.location }}
      cpu: 18
      memory_in_gb: 112
      cleanup: "always"
      is_big_containers_test: true

  stress-18cpu-144gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
    # Serializes execution
    needs: stress-18cpu-112gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 18cpu-144gb
      location: ${{ inputs.location }}
      cpu: 18
      memory_in_gb: 144
      cleanup: "always"
      is_big_containers_test: true

  # stress-18cpu-164gb:
  #   secrets: inherit
  #   # BigContainers regions
  #   if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
  #   # Serializes execution
  #   needs: stress-18cpu-144gb
  #   uses: ./.github/workflows/workload-stress-tests.yml
  #   with:
  #     id: 18cpu-164gb
  #     location: ${{ inputs.location }}
  #     cpu: 18
  #     memory_in_gb: 164
  #     cleanup: "always"
  #     is_big_containers_test: true

  stress-28cpu-96gb:
    secrets: inherit
    # BigContainers regions
    if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) && inputs.location == 'eastus2euap' }}
    # Serializes execution
    needs: stress-18cpu-144gb
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 28cpu-96gb
      location: ${{ inputs.location }}
      cpu: 28
      memory_in_gb: 96
      cleanup: "always"
      is_big_containers_test: true

  # stress-28cpu-164gb:
  #   secrets: inherit
  #   # BigContainers regions
  #   if: ${{ !cancelled() && contains(vars.ACI_BIG_CONTAINERS_REGION, format(',{0},', inputs.location)) }}
  #   # Serializes execution
  #   needs: stress-28cpu-96gb
  #   uses: ./.github/workflows/workload-stress-tests.yml
  #   with:
  #     id: 28cpu-164gb
  #     location: ${{ inputs.location }}
  #     cpu: 28
  #     memory_in_gb: 164
  #     cleanup: "always"
  #     is_big_containers_test: true
