name: High Spec - Japan East

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/high-spec-japaneast.yml

jobs:
  high-spec-japaneast:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: japaneast
