name: High Spec - Germany West Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/high-spec-germanywestcentral.yml
      - .github/workflows/high-spec.yml

jobs:
  high-spec-germanywestcentral:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: germanywestcentral
