name: High Spec - East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/high-spec-eastasia.yml
      - .github/workflows/high-spec.yml

jobs:
  high-spec-eastasia:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: eastasia
