name: High Spec - North Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '22 21 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-northeurope:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: northeurope
