name: High Spec - West US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '56 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-westus:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: westus
