name: High Spec

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/high-spec.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/high-spec.yml
  workflow_dispatch:
    inputs:
      location:
        type: string
        description: Test region
        required: true
  workflow_call:
    inputs:
      location:
        type: string
        description: Test region
        required: true

jobs:
  stress-4cpu-16gb:
    secrets: inherit
    # This should be available in all regions
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/workload-stress-tests.yml
    with:
      id: 4cpu-16gb
      location: ${{ inputs.location }}
      cpu: 4
      memory_in_gb: 16
      cleanup: "always"
