name: High Spec - UAE North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '45 6 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/high-spec-uaenorth.yml
      - .github/workflows/high-spec.yml

jobs:
  high-spec-uaenorth:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: uaenorth
