name: High Spec - East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '41 22 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-eastasia:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: eastasia
