name: High Spec - Malaysia West

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '11 23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-malaysiawest:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: malaysiawest
