name: High Spec - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '39 6 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  high-spec-eastus2euap:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: eastus2euap
