name: High Spec - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/high-spec-eastus2euap.yml

jobs:
  high-spec-eastus2euap:
    uses: ./.github/workflows/high-spec.yml
    secrets: inherit
    with:
      location: eastus2euap
