name: Perf - Central US EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '34 2 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-centraluseuap:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: centraluseuap
