name: Perf

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/perf-region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'
  workflow_dispatch:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:
  perf:
    if: ${{ !cancelled() }}
    name: perf
    secrets: inherit
    uses: ./.github/workflows/workload-perf.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: perf-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  perf-nonconf:
    if: ${{ !cancelled() }}
    name: perf-nonconf
    secrets: inherit
    uses: ./.github/workflows/workload-perf-nonconf.yml
    with:
      id: perf-nonconf
      location: ${{ inputs.location }}

  virtualclient:
    if: ${{ !cancelled() && inputs.location != 'centraluseuap' }}
    name: virtualclient
    secrets: inherit
    uses: ./.github/workflows/workload-virtualclient.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - short: openssl
            profileName: PERF-CPU-OPENSSL.json
          - short: compress
            profileName: PERF-COMPRESSION.json
          - short: fio
            profileName: custom-profile-FIO.json
          - short: hammerdb
            profileName: custom-profile-POSTGRESQL-HAMMERDB-TPCC.json
    with:
      id: virtualclient-${{ matrix.short }}
      location: ${{ inputs.location }}
      profileName: ${{ matrix.profileName }}

  virtualclient-cuseuap:
    if: ${{ !cancelled() && inputs.location == 'centraluseuap' }}
    name: virtualclient
    secrets: inherit
    uses: ./.github/workflows/workload-virtualclient.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - short: openssl
            profileName: PERF-CPU-OPENSSL.json
          - short: compress
            profileName: PERF-COMPRESSION.json
    with:
      id: virtualclient-${{ matrix.short }}
      location: ${{ inputs.location }}
      profileName: ${{ matrix.profileName }}
