name: Perf - West US 3

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '54 3 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-westus3:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: westus3
