name: Perf - South East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '24 9 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-southeastasia:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: southeastasia
