name: Perf - Belgium Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '57 1 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-belgiumcentral:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: belgiumcentral
