name: Perf - East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '44 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-eastasia:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: eastasia
