name: Perf - Italy North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '58 2 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-italynorth:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: italynorth
