name: Perf - South Africa West

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '18 3 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-southafricawest:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: southafricawest
