name: Perf - South Central US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '51 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-southcentralus:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: southcentralus
