name: Perf - West US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '25 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-westus:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: westus
