name: Perf - Japan East

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '35 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/perf-japaneast.yml

jobs:
  perf-japaneast:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: japaneast
