name: Perf - Sweden Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '30 23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-swedencentral:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: swedencentral
