name: Perf - Switzerland North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/perf-switzerlandnorth.yml

jobs:
  perf-switzerlandnorth:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: switzerlandnorth
