name: Perf - West Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '28 9 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-westeurope:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: westeurope
