name: Perf - East US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '42 2 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-eastus:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: eastus
