name: Perf - Switzerland North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '22 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-switzerlandnorth:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: switzerlandnorth
