name: Perf - Germany West Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '47 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-germanywestcentral:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: germanywestcentral
