name: Perf - Japan East

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '21 9 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  perf-japaneast:
    secrets: inherit
    uses: ./.github/workflows/perf-region.yml
    with:
      location: japaneast
