name: Region - East US 2

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '32 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  eastus2:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: eastus2
