name: Region - West Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '40 5 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-westeurope.yml

jobs:
  westeurope:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: westeurope

  zones:
    name: availability_zones
    secrets: inherit
    uses: ./.github/workflows/workload-availability-zones.yml
    strategy:
      fail-fast: false
      matrix:
        zone: ['1', '2']
    with:
      id: zone-${{ matrix.zone }}
      location: westeurope
      zone: ${{ matrix.zone }}
      policy_type: generated
