name: Region - Sweden Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '40 4 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-swedencentral.yml

jobs:
  swedencentral:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: swedencentral
