name: Region - South East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '29 15 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  southeastasia:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: southeastasia
