name: Region - South Africa North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '21 13 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  southafricanorth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: southafricanorth
