name: Region - West US 2

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '16 15 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  westus2:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: westus2
