name: Region - UAE North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '11 5 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  uaenorth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: uaenorth
