name: Region - Poland Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '37 13 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  polandcentral:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: polandcentral
