name: Region - South Central US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-southcentralus.yml

jobs:
  southcentralus:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: southcentralus
