name: Region - Central US EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-centraluseuap.yml

jobs:
  # centraluseuap:
  #   secrets: inherit
  #   uses: ./.github/workflows/region.yml
  #   with:
  #     location: centraluseuap

  genoa-cuseuap-regular:
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests.yml
    with:
      id: vm-genoa-cuseuap-regular-ws2025-6.1
      location: centraluseuap
      vmSize: Standard_DC8as_cc_v5
      cplatBlobName: ${{ vars.CPLAT_6_1_BLOB_NAME }}
      winFlavor: ws2025

  genoa-cuseuap-new-igvmfile:
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests.yml
    with:
      id: vm-genoa-cuseuap-nigvmf-ws2025-6.1
      location: centraluseuap
      vmSize: Standard_DC8as_cc_v5
      cplatBlobName: ${{ vars.CPLAT_6_1_IGVMFILE_BLOB_NAME }}
      winFlavor: ws2025
