name: Region

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region.yml
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'
      require_host_amd_cert:
        type: boolean
        description: Whether the info workload should fail if /security-context-*/host-amd-cert-base64 is missing
        default: true
      expect_uvm_signature:
        type: string
        description: Which UVM endorsement DID to validate against ('Prod' or 'Test')
        default: Prod
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'
      require_host_amd_cert:
        type: boolean
        description: Whether the info workload should fail if /security-context-*/host-amd-cert-base64 is missing
        default: true
      expect_uvm_signature:
        type: string
        description: Which UVM endorsement DID to validate against ('Prod' or 'Test')
        default: Prod

jobs:
  minimal:
    if: ${{ !cancelled() }}
    name: minimal
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: minimal-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      cpu: 1
      memory_in_gb: 1
      test_schedule: gh-daily

  info:
    if: ${{ !cancelled() }}
    name: info
    secrets: inherit
    needs: minimal
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        use_vnet: [true, false]
    with:
      id: info-${{ matrix.policy_type }}${{ matrix.use_vnet && '-vnet' || '' }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      use_vnet: ${{ matrix.use_vnet }}
      test_schedule: gh-daily
      require_host_amd_cert: ${{ inputs.require_host_amd_cert != false }}
      expect_uvm_signature: ${{ inputs.expect_uvm_signature || 'Prod' }}

  server:
    if: "${{ !cancelled() && !contains(vars.REGIONS_WITH_PROBLEMATIC_PUBLIC_IP, format(',{0},', inputs.location)) }}"
    name: server
    secrets: inherit
    needs: info
    uses: ./.github/workflows/workload-server.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: server-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  vnet:
    if: ${{ !cancelled() }}
    name: vnet
    secrets: inherit
    needs: server
    uses: ./.github/workflows/workload-vnet.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: vnet-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  managed-id:
    if: ${{ !cancelled() }}
    name: managed-id
    secrets: inherit
    needs: vnet
    uses: ./.github/workflows/workload-managed-identity.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        use_vnet: [true, false]
    with:
      id: managed-id-${{ matrix.policy_type }}${{ matrix.use_vnet && '-vnet' || '' }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      use_vnet: ${{ matrix.use_vnet }}
      test_schedule: gh-daily

  attestation:
    if: ${{ !cancelled() }}
    name: attestation
    secrets: inherit
    needs: managed-id
    uses: ./.github/workflows/workload-attestation.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: attestation-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  many-layers:
    if: ${{ !cancelled() }}
    name: many-layers
    secrets: inherit
    needs: attestation
    uses: ./.github/workflows/workload-many-layers.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated']
    with:
      id: many-layers-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  non-confidential:
    if: "${{ !cancelled() && !contains(vars.REGIONS_WITH_PROBLEMATIC_PUBLIC_IP, format(',{0},', inputs.location)) }}"
    name: non-confidential
    secrets: inherit
    needs: many-layers
    uses: ./.github/workflows/workload-non-confidential.yml
    with:
      id: non-confidential-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      test_schedule: gh-daily

  stress-tests:
    if: "${{ !cancelled() && !contains(vars.REGIONS_WITH_PROBLEMATIC_PUBLIC_IP, format(',{0},', inputs.location)) }}"
    name: stress-tests
    secrets: inherit
    needs: non-confidential
    uses: ./.github/workflows/workload-stress-tests.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        script: ['fio', 'tar', 'cpu', 'exec', 'cpu_fio', 'multicpu_fio']
    with:
      id: stress-${{ matrix.policy_type }}-${{ matrix.script }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      script: workload_${{ matrix.script }}
      test_schedule: gh-daily

  common-images:
    if: ${{ !cancelled() }}
    name: common-images
    secrets: inherit
    needs: stress-tests
    uses: ./.github/workflows/workload-common-images.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: common-images-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  workload-sidecar-with-fragments:
    if: ${{ !cancelled() }}
    name: workload-sidecar-with-fragments
    secrets: inherit
    needs: common-images
    uses: ./.github/workflows/workload-sidecar-with-fragments.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: sidecar-fragment-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  workload-sidecar-with-fragments-with-wait:
    if: ${{ !cancelled() }}
    name: workload-sidecar-with-fragments-with-wait
    secrets: inherit
    needs: workload-sidecar-with-fragments
    uses: ./.github/workflows/workload-sidecar-with-fragments-with-wait.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: sidecar-fragment-wait-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  thim:
    if: ${{ !cancelled() }}
    name: thim
    secrets: inherit
    needs: workload-sidecar-with-fragments-with-wait
    uses: ./.github/workflows/workload-thim.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        has_managed_identity: [true, false]
    with:
      id: thim-${{ matrix.policy_type }}${{ matrix.has_managed_identity && '-mi' || '' }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      has_managed_identity: ${{ matrix.has_managed_identity }}
      test_schedule: gh-daily

  skr:
    if: "${{ !cancelled() && !contains(vars.REGIONS_WITH_PROBLEMATIC_PUBLIC_IP, format(',{0},', inputs.location)) }}"
    name: skr
    secrets: inherit
    needs: thim
    uses: ./.github/workflows/workload-skr.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: skr-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  skr-fixed-policy:
    if: "${{ !cancelled() && !contains(vars.REGIONS_WITH_PROBLEMATIC_PUBLIC_IP, format(',{0},', inputs.location)) }}"
    name: skr-fixed-policy
    secrets: inherit
    needs: skr
    uses: ./.github/workflows/workload-skr-fixed-policy.yml
    with:
      id: skr-fixed-policy
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      test_schedule: gh-daily

  volume:
    if: ${{ !cancelled() }}
    name: volume
    secrets: inherit
    needs: skr-fixed-policy
    uses: ./.github/workflows/workload-volume.yml
    with:
      id: volume-generated
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: generated
      test_schedule: gh-daily

  net_liveness:
    if: ${{ !cancelled() }}
    name: net-liveness
    secrets: inherit
    needs: volume
    uses: ./.github/workflows/workload-net-liveness.yml
    with:
      id: net-liveness-allow_all
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      test_schedule: gh-daily

  secrets:
    if: ${{ !cancelled() }}
    name: secrets
    secrets: inherit
    needs: net_liveness
    uses: ./.github/workflows/workload-secrets.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: secrets-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  configmap:
    if: ${{ !cancelled() }}
    name: configmap
    secrets: inherit
    needs: secrets
    uses: ./.github/workflows/workload-configmap.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: configmap-${{ matrix.policy_type }}
      environment: ${{ inputs.environment || 'cacitesting.env' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily
