name: Region - Central India

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '2 2 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  centralindia:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: centralindia
