name: Region - South India

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '8 13 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  southindia:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: southindia
