name: Region - East US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '5 6 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  eastus:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: eastus
