name: Region - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '4 3 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  eastus2euap:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: eastus2euap

  stress-tests-noserver-allow-all:
    secrets: inherit
    uses: ./.github/workflows/workload-stress-tests-noserver.yml
    strategy:
      fail-fast: false
      matrix:
        script: ['fio', 'tar', 'cpu', 'exec', 'cpu_fio', 'multicpu_fio']
    with:
      id: stress-noserv-aa-${{ matrix.script }}
      location: eastus2euap
      policy_type: allow_all
      script: workload_${{ matrix.script }}
      cpu: 2

  stress-tests-noserver-debug:
    secrets: inherit
    uses: ./.github/workflows/workload-stress-tests-noserver.yml
    strategy:
      fail-fast: false
      matrix:
        script: ['fio', 'tar', 'cpu', 'exec', 'cpu_fio', 'multicpu_fio']
    with:
      id: stress-noserv-dbg-${{ matrix.script }}
      location: eastus2euap
      policy_type: debug
      script: workload_${{ matrix.script }}
      cpu: 2

  stress-test-noserver-generated:
    secrets: inherit
    uses: ./.github/workflows/workload-stress-tests-noserver.yml
    strategy:
      fail-fast: false
      matrix:
        script: ['fio', 'tar', 'cpu', 'exec', 'cpu_fio', 'multicpu_fio']
    with:
      id: stress-noserv-gen-${{ matrix.script }}
      location: eastus2euap
      policy_type: generated
      script: workload_${{ matrix.script }}
      cpu: 2
