name: Region - France South

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '20 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  francesouth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: francesouth
