name: Region - Brazil South

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region-brazilsouth.yml
  schedule:
    - cron: '29 4 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  brazilsouth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: brazilsouth
