name: Region - Japan East

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '7 4 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  japaneast:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: japaneast
