name: Region - Australia Central 2

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 1-23/2 * * *'
  workflow_dispatch:

jobs:
  australiacentral2:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: australiacentral2
