name: Region - Chile Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '28 6 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  chilecentral:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: chilecentral
