name: Region

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'
  workflow_dispatch:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:
  minimal:
    if: ${{ !cancelled() }}
    name: minimal
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: minimal-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  managed-id:
    if: ${{ !cancelled() }}
    name: managed-id
    secrets: inherit
    needs: minimal
    uses: ./.github/workflows/workload-managed-identity.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: managed-id-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  attestation:
    if: ${{ !cancelled() }}
    name: attestation
    secrets: inherit
    needs: managed-id
    uses: ./.github/workflows/workload-attestation.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: attestation-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  many-layers:
    if: ${{ !cancelled() }}
    name: many-layers
    secrets: inherit
    needs: attestation
    uses: ./.github/workflows/workload-many-layers.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated']
    with:
      id: many-layers-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  server:
    # public IP doesn't work here for now
    if: ${{ !cancelled() && inputs.location != 'eastus2euap' }}
    name: server
    secrets: inherit
    needs: many-layers
    uses: ./.github/workflows/workload-server.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: server-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  server-with-wait:
    # public IP doesn't work here for now
    if: ${{ !cancelled() && inputs.location != 'eastus2euap' }}
    name: server-with-wait
    secrets: inherit
    needs: server
    uses: ./.github/workflows/workload-server-with-wait.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: server-with-wait-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  non-confidential:
    if: ${{ !cancelled() }}
    name: non-confidential
    secrets: inherit
    needs: server-with-wait
    uses: ./.github/workflows/workload-non-confidential.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['allow_all']
    with:
      id: non-confidential-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  stress-tests:
    if: ${{ !cancelled() && inputs.location != 'eastus2euap' }}
    name: stress-tests
    secrets: inherit
    needs: non-confidential
    uses: ./.github/workflows/workload-stress-tests.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        script: ['fio', 'tar', 'cpu', 'exec', 'cpu_fio', 'multicpu_fio']
    with:
      id: stress-${{ matrix.policy_type }}-${{ matrix.script }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      script: workload_${{ matrix.script }}
      useNormalSidecar: true

  info:
    if: ${{ !cancelled() }}
    name: info
    secrets: inherit
    needs: stress-tests
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: info-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  perf:
    if: ${{ !cancelled() }}
    name: perf
    secrets: inherit
    needs: info
    uses: ./.github/workflows/workload-perf.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: perf-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  perf-nonconf:
    if: ${{ !cancelled() }}
    name: perf-nonconf
    secrets: inherit
    needs: perf
    uses: ./.github/workflows/workload-perf-nonconf.yml
    with:
      id: perf-nonconf
      location: ${{ inputs.location }}

  vnet:
    if: ${{ !cancelled() }}
    name: vnet
    secrets: inherit
    needs: perf-nonconf
    uses: ./.github/workflows/workload-vnet.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: vnet-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  common-images:
    if: ${{ !cancelled() }}
    name: common-images
    secrets: inherit
    needs: vnet
    uses: ./.github/workflows/workload-common-images.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: common-images-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  workload-sidecar-with-fragments:
    if: ${{ !cancelled() }}
    name: workload-sidecar-with-fragments
    secrets: inherit
    needs: common-images
    uses: ./.github/workflows/workload-sidecar-with-fragments.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: sidecar-fragment-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  vm-stress-curr-ws2025:
    if: ${{ !cancelled() && inputs.location != '' && contains(vars.WS2025_VM_REGIONS, inputs.location) }}
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests.yml
    with:
      id: vm-stress-curr-ws2025-6.1
      location: ${{ inputs.location }}
      cplatBlobName: ${{ vars.CPLAT_CURR_BLOB_NAME }}
      winFlavor: ws2025

  vm-stress-curr-ws2022:
    if: ${{ !cancelled() && inputs.location != '' && contains(vars.WS2022_VM_REGIONS, inputs.location) }}
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests.yml
    with:
      id: vm-stress-curr-ws2022-6.1
      location: ${{ inputs.location }}
      cplatBlobName: ${{ vars.CPLAT_CURR_BLOB_NAME }}
      winFlavor: ws2022

  vm-stress-next-6-1-ws2025:
    if: ${{ !cancelled() && inputs.location != '' && contains(vars.WS2025_VM_REGIONS, inputs.location) }}
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests.yml
    with:
      id: vm-stress-next-ws2025-6.1
      location: ${{ inputs.location }}
      cplatBlobName: ${{ vars.CPLAT_NEXT_6_1_BLOB_NAME }}
      winFlavor: ws2025

  vm-stress-next-hard-6-1-ws2025:
    if: ${{ !cancelled() && inputs.location != '' && contains(vars.WS2025_VM_REGIONS, inputs.location) }}
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests-hard.yml
    with:
      id: vm-stress-next-hard-ws2025-6.1
      location: ${{ inputs.location }}
      cplatBlobName: ${{ vars.CPLAT_NEXT_6_1_BLOB_NAME }}
      winFlavor: ws2025

  perf-cvm:
    if: ${{ !cancelled() && inputs.location == 'uaenorth' }}
    secrets: inherit
    uses: ./.github/workflows/workload-perf-cvm.yml
    strategy:
      fail-fast: false
      matrix:
        vmSize: ['DC4as_v5', 'DC8as_v5']
    with:
      id: perf-cvm-${{ matrix.vmSize }}
      location: ${{ inputs.location }}
      vmSize: Standard_${{ matrix.vmSize }}

  perf-regular-vm:
    if: ${{ !cancelled() && inputs.location == 'uaenorth' }}
    secrets: inherit
    uses: ./.github/workflows/workload-perf-regular-vm.yml
    strategy:
      fail-fast: false
      matrix:
        vmSize: ['D4as_v5', 'D8as_v5']
    with:
      id: perf-regular-vm-${{ matrix.vmSize }}
      location: ${{ inputs.location }}
      vmSize: Standard_${{ matrix.vmSize }}
