name: Region - Germany West Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '52 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  germanywestcentral:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: germanywestcentral
