name: Region - Korea Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '28 10 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  koreacentral:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: koreacentral
