name: Region - Australia Central 2

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '1 2 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  australiacentral2:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: australiacentral2
