name: Region - Switzerland North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '32 15 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  switzerlandnorth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: switzerlandnorth
