name: Region - Korea South

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '27 11 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  koreasouth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: koreasouth
