name: Region - Brazil South

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region-brazilsouth.yml
  schedule:
    - cron: '0 1-21/2 * * *'
  workflow_dispatch:

jobs:
  brazilsouth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: brazilsouth
