name: Region - Switzerland North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '40 5 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-switzerlandnorth.yml

jobs:
  switzerlandnorth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: switzerlandnorth
