name: Region - Sweden Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '14 15 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  swedencentral:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: swedencentral
