name: Region - Central US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '56 5 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  centralus:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: centralus
