name: Region

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'
  workflow_dispatch:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:
  minimal:
    if: ${{ !cancelled() }}
    name: minimal
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: minimal-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      cpu: 1
      memory_in_gb: 1
      test_schedule: gh-daily

  info:
    if: ${{ !cancelled() }}
    name: info
    secrets: inherit
    needs: minimal
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        use_vnet: [true, false]
    with:
      id: info-${{ matrix.policy_type }}${{ matrix.use_vnet && '-vnet' || '' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      use_vnet: ${{ matrix.use_vnet }}
      test_schedule: gh-daily

  server:
    if: ${{ !cancelled() }}
    name: server
    secrets: inherit
    needs: info
    uses: ./.github/workflows/workload-server.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: server-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  vnet:
    if: ${{ !cancelled() }}
    name: vnet
    secrets: inherit
    needs: server
    uses: ./.github/workflows/workload-vnet.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: vnet-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  managed-id:
    if: ${{ !cancelled() }}
    name: managed-id
    secrets: inherit
    needs: vnet
    uses: ./.github/workflows/workload-managed-identity.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        use_vnet: [true, false]
    with:
      id: managed-id-${{ matrix.policy_type }}${{ matrix.use_vnet && '-vnet' || '' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      use_vnet: ${{ matrix.use_vnet }}
      test_schedule: gh-daily

  attestation:
    if: ${{ !cancelled() }}
    name: attestation
    secrets: inherit
    needs: managed-id
    uses: ./.github/workflows/workload-attestation.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: attestation-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  many-layers:
    if: ${{ !cancelled() }}
    name: many-layers
    secrets: inherit
    needs: attestation
    uses: ./.github/workflows/workload-many-layers.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated']
    with:
      id: many-layers-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  non-confidential:
    if: ${{ !cancelled() }}
    name: non-confidential
    secrets: inherit
    needs: many-layers
    uses: ./.github/workflows/workload-non-confidential.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['allow_all']
    with:
      id: non-confidential-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  stress-tests:
    if: ${{ !cancelled() }}
    name: stress-tests
    secrets: inherit
    needs: non-confidential
    uses: ./.github/workflows/workload-stress-tests.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        script: ['fio', 'tar', 'cpu', 'exec', 'cpu_fio', 'multicpu_fio']
    with:
      id: stress-${{ matrix.policy_type }}-${{ matrix.script }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      script: workload_${{ matrix.script }}
      test_schedule: gh-daily

  common-images:
    if: ${{ !cancelled() }}
    name: common-images
    secrets: inherit
    needs: stress-tests
    uses: ./.github/workflows/workload-common-images.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: common-images-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  workload-sidecar-with-fragments:
    if: ${{ !cancelled() }}
    name: workload-sidecar-with-fragments
    secrets: inherit
    needs: common-images
    uses: ./.github/workflows/workload-sidecar-with-fragments.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: sidecar-fragment-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  workload-sidecar-with-fragments-with-wait:
    if: ${{ !cancelled() }}
    name: workload-sidecar-with-fragments-with-wait
    secrets: inherit
    needs: workload-sidecar-with-fragments
    uses: ./.github/workflows/workload-sidecar-with-fragments-with-wait.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: sidecar-fragment-wait-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily

  thim:
    if: ${{ !cancelled() }}
    name: thim
    secrets: inherit
    needs: workload-sidecar-with-fragments-with-wait
    uses: ./.github/workflows/workload-thim.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        has_managed_identity: [true, false]
    with:
      id: thim-${{ matrix.policy_type }}${{ matrix.has_managed_identity && '-mi' || '' }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      has_managed_identity: ${{ matrix.has_managed_identity }}
      test_schedule: gh-daily

  skr:
    if: ${{ !cancelled() }}
    name: skr
    secrets: inherit
    needs: thim
    uses: ./.github/workflows/workload-skr.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: skr-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      test_schedule: gh-daily
