name: Uptime - South East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '25 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  uptime:
    secrets: inherit
    uses: ./.github/workflows/uptime.yml
    with:
      location: southeastasia
