name: VM Custom UVM (Daily)

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '38 7 * * *'  # managed by scripts/spread_out_schedules.py
jobs:
  vm-custom-uvm:
    uses: ./.github/workflows/vm-custom-uvm.yml
    secrets: inherit
    with:
      uvmBlobName: "azurelinux-uvm"