name: VM - Central US EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '35 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-centraluseuap:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: centraluseuap
