name: VM - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '24 1 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-eastus2euap:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: eastus2euap
