name: VM - East US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '12 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-eastus:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: eastus
