name: VM - East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '36 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-eastasia:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: eastasia
