name: VM - Germany West Central

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '43 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-germanywestcentral:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: germanywestcentral
