name: VM Workload - Idle server

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/vm-idle.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC8as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      winFlavor:
        type: choice
        description: The Windows version of the image
        default: ws2025
        options:
          - ws2022
          - ws2025
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC8as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      winFlavor:
        type: string
        description: The Windows version of the image
        default: ws2025

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: vm
  TEST_NAME: VM Workload - Idle server
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'vm-idle' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}/test-containers/stress-tests-server-alpine
  TAG: latest
  MANAGED_IDENTITY: cacidashboard
  STORAGE_ACCOUNT: cacitestingstorage
  LOCATION: ${{ inputs.location || 'uaenorth' }}
  CLEANUP: ${{ inputs.cleanup }}
  USE_NORMAL_SIDECAR: true
  VM_SIZE: ${{ inputs.vmSize || 'Standard_DC8as_cc_v5' }}
  VM_IMAGE: ${{ inputs.vmImage || '' }}
  USE_OFFICIAL_IMAGES: ${{ inputs.vmImage == '' && 'true' || '' }}
  CPLAT_BLOB_NAME: ${{ inputs.cplatBlobName || vars.CPLAT_6_1_BLOB_NAME }}
  WIN_FLAVOR: ${{ inputs.winFlavor || 'ws2025' }}
  VM_ZONE: ${{ inputs.zone || '' }}

jobs:
  vm-idle:
    name: ${{ inputs.id || 'vm-idle' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        run: c-aci-testing images pull workloads/stress_tests

      # The security policy has to be allow_all for exec-based checks to work
      - name: Fill in allow_all security policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Fill in allow_all security policy'
          c-aci-testing policies gen workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --policy-type allow_all
          cat workloads/stress_tests/policy_stress_tests.rego

      - name: Deploy VM with containerplat
        run: |
          ./scripts/vm_create_traced.sh

      - name: Deploy Container Group (idle, 2cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (idle, 2cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=2
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=4
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_idle'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_idle

      - name: Print info
        run: scripts/vm_print_info.sh

      - name: Deploy Container Group (idle2, 2cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (idle2, 2cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=2
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=4
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_idle'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_idle2

      - name: Deploy Container Group (idle3, 1cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (idle3, 1cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=1
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=1
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_idle'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_idle3

      - name: Start check loop on VM
        run: |
          ./scripts/tracing/trace_step.py --start 'Start check loop on VM'
          c-aci-testing vm cp_into --deployment-name $DEPLOYMENT_NAME \
            scripts/vm_helpers \
            'C:\vm_helpers' \
            'C:\vm_helpers\start_check_loop.ps1 -checkArgs "-checkInterval 30 -additionalChecksScript check_stress_tests_http.ps1"'

      - name: Poll VM for check results
        run: |
          ./scripts/tracing/trace_step.py --start 'Poll VM for check results'
          set +e
          consecutive_fail_count=0
          for i in {1..20}; do
            sleep 120
            c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME 'C:\check_loop.log' > check.log
            if [ $? -ne 0 ]; then
              echo Error: Failed to poll VM for check log
              consecutive_fail_count=$((consecutive_fail_count+1))
              if [ $consecutive_fail_count -gt 3 ]; then
                exit 1
              fi
            else
              consecutive_fail_count=0
              echo Last 20 lines of check_loop.log:
              tail -n 20 check.log
            fi
          done
          exit 0

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Check for errors
        run: |
          ./scripts/tracing/trace_step.py --start 'Check for errors'
          set +e
          echo Full check_loop.log:
          cat check.log
          err_cnt=$(grep -F ERROR check.log | wc -l)
          if [ "$err_cnt" -gt 0 ]; then
            echo Found $err_cnt errors in check log.
            ./scripts/tracing/trace_step.py --complete --err "Found $err_cnt errors in check log." \
              --output "num_errors=$err_cnt"
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete --output "num_errors=0"
          exit 0

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Check dmesg
        if: always()
        run: ./scripts/vm_check_dmesg.sh

      - name: Container output
        if: always()
        run: |
          ./scripts/vm_check_container_output.sh

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Remove VM
        if: always()
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vm remove --deployment-name $DEPLOYMENT_NAME
            # Don't leave VM hanging around even if deployment disappears
            az vm delete \
              --resource-group $RESOURCE_GROUP \
              --name ${DEPLOYMENT_NAME}-vm \
              --yes --force-deletion yes --verbose || true
          fi
