name: VM - Italy North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '36 1 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-italynorth:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: italynorth
