name: VM - Italy North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '55 6 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vm-italynorth.yml

jobs:
  vm-italynorth:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: italynorth
