name: VM - Malaysia West

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '40 1 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-malaysiawest:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: malaysiawest
