name: VM Simple

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/vm-simple.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
      - scripts/vm_print_info.sh
  push:
    paths:
      - .github/workflows/vm-simple.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
      - scripts/vm_print_info.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC4as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      uvmBlobName:
        type: string
        description: The name of the blob for UVM image
        default: ''
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC4as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      uvmBlobName:
        type: string
        description: The name of the blob for UVM image
        default: ''
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: vm
  TEST_NAME: VM Simple
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'vm-simple' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION_ACI }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}/test-containers
  TAG: latest
  STORAGE_ACCOUNT: cacitestingstorageaci
  LOCATION: ${{ inputs.location || 'uaenorth' }}
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'uaenorth' }}
  CLEANUP: ${{ inputs.cleanup }}
  VM_SIZE: ${{ inputs.vmSize || 'Standard_DC8as_cc_v5' }}
  VM_IMAGE: ${{ inputs.vmImage || '' }}
  USE_OFFICIAL_IMAGES: ${{ inputs.vmImage == '' && 'true' || '' }}
  CPLAT_BLOB_NAME: ${{ inputs.cplatBlobName || vars.CPLAT_NEXT_6_1_BLOB_NAME }}
  WIN_FLAVOR: 'ws2025'
  VM_ZONE: ${{ inputs.zone || '' }}
  UVM_KERNEL: ${{ inputs.uvmBlobName != '' && format('{0}/kernel.vmgs', inputs.uvmBlobName) || '' }}
  UVM_ROOTFS: ${{ inputs.uvmBlobName != '' && format('{0}/rootfs-verity.vhd', inputs.uvmBlobName) || '' }}
  UVM_CONTAINERD_SHIM: ${{ inputs.uvmBlobName != '' && format('{0}/containerd-shim-runhcs-v1.exe', inputs.uvmBlobName) || '' }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}

jobs:
  vm-simple:
    name: ${{ inputs.id || 'vm-simple' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Downgrade Azure CLI
        env:
          AZ_CLI_VERSION: "2.81.0"
        run: ./scripts/install-az-cli.sh

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ACI }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        run: c-aci-testing images pull workloads/server

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/server --deployment-name $DEPLOYMENT_NAME --policy-type allow_all
          cat workloads/server/policy_server.rego
          c-aci-testing policies gen workloads/info --deployment-name $DEPLOYMENT_NAME --policy-type allow_all
          if ! cmp workloads/server/policy_server.rego workloads/info/policy_info.rego; then
            echo "Error: policies for server and info workloads differ for some reason, even though both are allow_all"
            echo "info:"
            cat workloads/info/policy_info.rego
          fi

      - name: Download and extract UVM blob if specified
        if: ${{ inputs.uvmBlobName != '' }}
        run: |
          az storage blob download \
            --account-name $STORAGE_ACCOUNT \
            --container-name container \
            --name "${{ inputs.uvmBlobName }}" \
            --file "${{ inputs.uvmBlobName }}.tar" \
            --auth-mode login
          mkdir -p ${{ inputs.uvmBlobName }}
          tar -xf ${{ inputs.uvmBlobName }}.tar -C ${{ inputs.uvmBlobName }}

      - name: Deploy VM
        run: |
          ./scripts/vm_create_traced.sh

      - name: Deploy Container Group (server)
        run: |
          ./scripts/tracing/trace_step.py --start 'vm runc'
          c-aci-testing vm runc workloads/server

      - name: Print info
        run: scripts/vm_print_info.sh

      - name: Deploy Container Group (info)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (info)'
          c-aci-testing aci param_set workloads/info --parameter 'requireHostAmdCert=false'
          c-aci-testing vm runc workloads/info --deployment-name $DEPLOYMENT_NAME --prefix lcow_info

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Check dmesg
        if: always()
        run: |
          ./scripts/tracing/trace_step.py --start 'Check dmesg'
          c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'Get-Item C:\*\dmesg*.log | foreach { echo ""; echo ""; echo $_.FullName; cat -Raw $_ } > C:\all-dmesg.log'
          c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME 'C:\all-dmesg.log' > dmesg.log
          cat dmesg.log
          # will call trace --complete
          ./scripts/_check_dmesg.sh "dmesg.log"

      - name: Container output
        if: always()
        run: |
          ./scripts/vm_check_container_output.sh

      - name: 'Check info log contains "info: success"'
        run: |
          ./scripts/tracing/trace_step.py --start 'Check info log has success'
          ok=1
          grep -q "info: success" container_output.log || ok=0
          if [ $ok -ne 1 ]; then
            ./scripts/tracing/trace_step.py --complete --err 'info log does not contain success'
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete --strict

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Remove VM
        if: always()
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vm remove --deployment-name $DEPLOYMENT_NAME
            # Don't leave VM hanging around even if deployment disappears
            az vm delete \
              --resource-group $RESOURCE_GROUP \
              --name ${DEPLOYMENT_NAME}-vm \
              --yes --force-deletion yes --verbose || true
          fi
