name: VM - South Central US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '51 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-southcentralus:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: southcentralus
