name: VM - Southeast Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '4 23 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-southeastasia:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: southeastasia
