name: VM - UAE North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '58 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-uaenorth:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: uaenorth
