name: VM Workload - Stress Tests

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/vm-workload-stress-tests.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC8as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      uvmBlobName:
        type: string
        description: The name of the blob for UVM image
        default: ''
      doStressTestsHttpChecks:
        type: boolean
        description: Whether to do curl checks during the run
        default: false
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC8as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      uvmBlobName:
        type: string
        description: The name of the blob for UVM image
        default: ''
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''
      doStressTestsHttpChecks:
        type: boolean
        description: Whether to do curl checks during the run
        default: false

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: vm
  TEST_NAME: VM Workload - Stress Tests
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'vm-stress' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}/test-containers/stress-tests-server-alpine
  TAG: latest
  STORAGE_ACCOUNT: cacitestingstorage
  LOCATION: ${{ inputs.location || 'uaenorth' }}
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'uaenorth' }}
  CLEANUP: ${{ inputs.cleanup }}
  VM_SIZE: ${{ inputs.vmSize || 'Standard_DC8as_cc_v5' }}
  VM_IMAGE: ${{ inputs.vmImage || '' }}
  USE_OFFICIAL_IMAGES: ${{ inputs.vmImage == '' && 'true' || '' }}
  CPLAT_BLOB_NAME: ${{ inputs.cplatBlobName || vars.CPLAT_NEXT_6_1_BLOB_NAME }}
  WIN_FLAVOR: 'ws2025'
  VM_ZONE: ${{ inputs.zone || '' }}
  UVM_KERNEL: ${{ inputs.uvmBlobName != '' && format('{0}/kernel.vmgs', inputs.uvmBlobName) || '' }}
  UVM_ROOTFS: ${{ inputs.uvmBlobName != '' && format('{0}/rootfs-verity.vhd', inputs.uvmBlobName) || '' }}
  UVM_CONTAINERD_SHIM: ${{ inputs.uvmBlobName != '' && format('{0}/containerd-shim-runhcs-v1.exe', inputs.uvmBlobName) || '' }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}
  DO_STRESS_TESTS_HTTP_CHECKS: ${{ inputs.doStressTestsHttpChecks }}

jobs:
  vm-stress-tests:
    name: ${{ inputs.id || 'vm-stress-tests' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # vm run-command invoke is broken from 2.78 - see
      # https://github.com/Azure/azure-cli/issues/32258.  Use an older version
      # of az-cli for VM tests until this is fixed.
      - name: Downgrade Azure CLI
        env:
          AZ_CLI_VERSION: "2.77.0"
        run: ./scripts/install-az-cli.sh

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        run: c-aci-testing images pull workloads/stress_tests

      # The security policy has to be allow_all for exec-based checks to work
      - name: Fill in allow_all security policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Fill in allow_all security policy'
          c-aci-testing policies gen workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --policy-type allow_all
          cat workloads/stress_tests/policy_stress_tests.rego

      - name: Download and extract UVM blob if specified
        if: ${{ inputs.uvmBlobName != '' }}
        run: |
          az storage blob download \
            --account-name $STORAGE_ACCOUNT \
            --container-name container \
            --name "${{ inputs.uvmBlobName }}" \
            --file "${{ inputs.uvmBlobName }}.tar" \
            --auth-mode login
          mkdir -p ${{ inputs.uvmBlobName }}
          tar -xf ${{ inputs.uvmBlobName }}.tar -C ${{ inputs.uvmBlobName }}

      - name: Deploy VM with containerplat
        run: |
          ./scripts/vm_create_traced.sh

      - name: Deploy Container Group (fio, 2cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (fio, 2cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=2
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=4
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_fio'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_fio

      - name: Print info
        run: scripts/vm_print_info.sh

      - name: Deploy Container Group (cpu, 2cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (cpu, 2cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=2
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=4
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_cpu'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_cpu

      - name: Deploy Container Group (tar, 1cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (tar, 1cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=1
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=1
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_tar'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_tar

      - name: Do check loop on VM
        run: |
          mkdir -p ./logs
          maybe_do_stress_tests_http_checks=""
          if [ "$DO_STRESS_TESTS_HTTP_CHECKS" = "true" ]; then
            maybe_do_stress_tests_http_checks="--stress-tests-http-checks"
          fi
          ./scripts/vm_do_check_loop.py --check-for-secs 3600 --out-dir ./logs $maybe_do_stress_tests_http_checks

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Check for errors
        if: always()
        run: |
          ./scripts/tracing/trace_step.py --start 'Check for errors'
          set +e
          echo Full check_loop.log:
          cat ./logs/check_loop.log
          err_cnt=$(grep -F ERROR ./logs/check_loop.log | wc -l)
          if [ "$err_cnt" -gt 2 ]; then
            echo Found $err_cnt errors in check log.
            ./scripts/tracing/trace_step.py --complete --err "Found $err_cnt errors in check log." \
              --output "num_errors=$err_cnt"
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete --output "num_errors=0"
          exit 0

      - name: Check dmesg
        if: always()
        run: |
          ./scripts/tracing/trace_step.py --start "Check dmesg"
          set +e
          has_error=0
          echo -n '' > combined_dmesg.log
          cd logs
          for file in $(find . -name 'dmesg*.log'); do
            echo "$file:"
            cat "$file"
            echo
            echo
            cat "$file" >> ../combined_dmesg.log
          done
          cd ..
          # will call trace --complete
          ./scripts/_check_dmesg.sh combined_dmesg.log

      - name: Container output
        if: always()
        run: |
          set +e
          for file in $(find logs -name 'container_log_*.log'); do
            echo "$file:"
            cat "$file"
            # Will trace steps
            ./scripts/parse_container_output.py "$file" --fail-on-error
            echo
            echo
          done

      - name: Remove VM
        if: always()
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vm remove --deployment-name $DEPLOYMENT_NAME
            # Don't leave VM hanging around even if deployment disappears
            az vm delete \
              --resource-group $RESOURCE_GROUP \
              --name ${DEPLOYMENT_NAME}-vm \
              --yes --force-deletion yes --verbose || true
          fi
