name: VM Workload - Stress Tests

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/vm-workload-stress-tests.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC8as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      winFlavor:
        type: choice
        description: The Windows version of the image
        default: ws2025
        options:
          - ws2022
          - ws2025
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC8as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      winFlavor:
        type: string
        description: The Windows version of the image
        default: ws2025

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: vm
  TEST_NAME: VM Workload - Stress Tests
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'vm-stress' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboard.azurecr.io
  MANAGED_IDENTITY: cacidashboard
  STORAGE_ACCOUNT: cacitestingstorage
  LOCATION: ${{ inputs.location || 'uaenorth' }}
  CLEANUP: ${{ inputs.cleanup }}
  USE_NORMAL_SIDECAR: true
  VM_SIZE: ${{ inputs.vmSize || 'Standard_DC8as_cc_v5' }}
  VM_IMAGE: ${{ inputs.vmImage || ( inputs.winFlavor == 'ws2022' && secrets.VM_IMAGE_WS2022 || secrets.VM_IMAGE_WS2025 ) }}
  CPLAT_BLOB_NAME: ${{ inputs.cplatBlobName || vars.CPLAT_6_1_BLOB_NAME }}
  WIN_FLAVOR: ${{ inputs.winFlavor || 'ws2025' }}
  VM_ZONE: ${{ inputs.zone || '' }}

jobs:
  vm-stress-tests:
    name: ${{ inputs.id || 'vm-stress-tests' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Deploy VM with containerplat
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy VM with containerplat'
          c-aci-testing vm create --deployment-name $DEPLOYMENT_NAME

      - name: Use precise current time as tag
        run: |
          TAG=$(date "+%Y%m%d-%H%M%S.%N")
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build image
        run: |
          ./scripts/tracing/trace_step.py --start 'Build and push image'
          c-aci-testing images build workloads/stress_tests

      - name: Push image
        run: c-aci-testing images push workloads/stress_tests

      - name: Set parameters
        run: |
          c-aci-testing aci param_set workloads/stress_tests --parameter "useNormalSidecar=true"
          echo stress_tests.bicepparam:
          cat workloads/stress_tests/stress_tests.bicepparam

      # The security policy has to be allow_all for exec-based checks to work
      - name: Fill in allow_all security policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Fill in allow_all security policy'
          c-aci-testing policies gen workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --policy-type allow_all
          cat workloads/stress_tests/policy_stress_tests.rego

      # The Atlas image often reboots automatically on first boot for unknown reasons, but does not happen more than once.
      # So we just wait for a bit to let that happen.
      # It is also more realistic to not start spinning up containers immediately after the VM is created.
      - name: Wait for any pending first-boot reboots
        run: |
          ./scripts/tracing/trace_step.py --start 'Wait for any pending first-boot reboots'
          sleep 500

      # OCID token refresh breaks after 5 min
      # https://github.com/Azure/azure-cli/issues/28708
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Deploy Container Group (fio, 2cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (fio, 2cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=2
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=4
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_fio'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_fio

      - name: Print info
        run: scripts/vm_print_info.sh

      - name: Deploy Container Group (cpu, 2cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (cpu, 2cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=2
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=4
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_cpu'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_cpu

      - name: Deploy Container Group (tar, 1cpu)
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group (tar, 1cpu)'
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=1
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=1
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='workload_tar'"
          c-aci-testing vm runc workloads/stress_tests --deployment-name $DEPLOYMENT_NAME --prefix lcow_tar

      - name: Start check loop on VM
        run: |
          ./scripts/tracing/trace_step.py --start 'Start check loop on VM'
          c-aci-testing vm cp_into --deployment-name $DEPLOYMENT_NAME \
            scripts/vm_helpers \
            'C:\vm_helpers' \
            'C:\vm_helpers\start_check_loop.ps1 -checkArgs "-checkInterval 30 -additionalChecksScript check_stress_tests_http.ps1"'

      - name: Poll VM for check results
        run: |
          ./scripts/tracing/trace_step.py --start 'Poll VM for check results'
          set +e
          consecutive_fail_count=0
          for i in {1..20}; do
            sleep 120
            c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME 'C:\check_loop.log' > check.log
            if [ $? -ne 0 ]; then
              echo Error: Failed to poll VM for check log
              consecutive_fail_count=$((consecutive_fail_count+1))
              if [ $consecutive_fail_count -gt 3 ]; then
                exit 1
              fi
            else
              consecutive_fail_count=0
              echo Last 20 lines of check_loop.log:
              tail -n 20 check.log
            fi
          done
          exit 0

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Check for errors
        run: |
          ./scripts/tracing/trace_step.py --start 'Check for errors'
          set +e
          echo Full check_loop.log:
          cat check.log
          err_cnt=$(grep -F ERROR check.log | wc -l)
          if [ "$err_cnt" -gt 0 ]; then
            echo Found $err_cnt errors in check log.
            ./scripts/tracing/trace_step.py --complete --err "Found $err_cnt errors in check log." \
              --output "num_errors=$err_cnt"
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete
          exit 0

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Check dmesg
        if: always()
        run: ./scripts/vm_check_dmesg.sh

      - name: Container output (workload)
        if: always()
        run: |
          ./scripts/tracing/trace_step.py --start 'Container output (workload)'
          for lcow_dir in lcow_fio lcow_cpu lcow_tar; do
            echo "Container output for $lcow_dir:"
            c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME "C:\\$lcow_dir\\container_log_stress_tests_workload.log"
          done

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Remove VM
        if: always()
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vm remove --deployment-name $DEPLOYMENT_NAME
            # Don't leave VM hanging around even if deployment disappears
            az vm delete \
              --resource-group $RESOURCE_GROUP \
              --name ${DEPLOYMENT_NAME}-vm \
              --yes --force-deletion yes --verbose || true
          fi
