name: VM - West Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '30 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vm-westeurope:
    secrets: inherit
    uses: ./.github/workflows/vm-region.yml
    with:
      location: westeurope
