name: VM Fragment workload

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/vm-workload-fragment.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
      - scripts/vm_print_info.sh
  push:
    paths:
      - .github/workflows/vm-workload-fragment.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
      - scripts/vm_print_info.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC4as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      uvmBlobName:
        type: string
        description: The name of the blob for UVM image
        default: ''
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The zone to deploy to
        required: false
        default: ''
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC4as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      uvmBlobName:
        type: string
        description: The name of the blob for UVM image
        default: ''
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: vm
  TEST_NAME: VM Fragment workload
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'vm-simple' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboard.azurecr.io
  TAG: latest
  STORAGE_ACCOUNT: cacitestingstorage
  LOCATION: ${{ inputs.location || 'uaenorth' }}
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'uaenorth' }}
  CLEANUP: ${{ inputs.cleanup }}
  VM_SIZE: ${{ inputs.vmSize || 'Standard_DC8as_cc_v5' }}
  VM_IMAGE: ${{ inputs.vmImage || '' }}
  USE_OFFICIAL_IMAGES: ${{ inputs.vmImage == '' && 'true' || '' }}
  CPLAT_BLOB_NAME: ${{ inputs.cplatBlobName || vars.CPLAT_NEXT_6_1_BLOB_NAME }}
  WIN_FLAVOR: 'ws2025'
  VM_ZONE: ${{ inputs.zone || '' }}
  UVM_KERNEL: ${{ inputs.uvmBlobName != '' && format('{0}/kernel.vmgs', inputs.uvmBlobName) || '' }}
  UVM_ROOTFS: ${{ inputs.uvmBlobName != '' && format('{0}/rootfs-verity.vhd', inputs.uvmBlobName) || '' }}
  UVM_CONTAINERD_SHIM: ${{ inputs.uvmBlobName != '' && format('{0}/containerd-shim-runhcs-v1.exe', inputs.uvmBlobName) || '' }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}

jobs:
  vm-fragment:
    name: ${{ inputs.id || 'vm-fragment' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # vm run-command invoke is broken from 2.78 - see
      # https://github.com/Azure/azure-cli/issues/32258.  Use an older version
      # of az-cli for VM tests until this is fixed.
      - name: Downgrade Azure CLI
        env:
          AZ_CLI_VERSION: "2.77.0"
        run: ./scripts/install-az-cli.sh

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Use precise current time as tag
        run: |
          export TAG=$(date "+%Y%m%d-%H%M%S.%N")
          echo TAG: $TAG
          . workloads/workload-sidecar-with-fragments/setup_vars.sh

          echo "REPO=$REPO" >> $GITHUB_ENV
          echo "SIDECAR_REPO_A=$SIDECAR_REPO_A" >> $GITHUB_ENV
          echo "SIDECAR_REPO_B=$SIDECAR_REPO_B" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "SIDECAR_TAG=$SIDECAR_TAG" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "SIDECAR_IMAGE_A=$SIDECAR_IMAGE_A" >> $GITHUB_ENV
          echo "SIDECAR_IMAGE_B=$SIDECAR_IMAGE_B" >> $GITHUB_ENV
          echo "FEED=$FEED" >> $GITHUB_ENV

      - name: Build and push image and fragments (make)
        run: |
          ./scripts/tracing/trace_step.py --start 'Build and push image and fragments (make)'
          cd workloads/workload-sidecar-with-fragments
          make

      - name: Generate VM scripts
        run: |
          cd workloads/workload-sidecar-with-fragments
          make generate_vm_scripts

      - name: Download and extract UVM blob if specified
        if: ${{ inputs.uvmBlobName != '' }}
        run: |
          az storage blob download \
            --account-name $STORAGE_ACCOUNT \
            --container-name container \
            --name "${{ inputs.uvmBlobName }}" \
            --file "${{ inputs.uvmBlobName }}.tar" \
            --auth-mode login
          mkdir -p ${{ inputs.uvmBlobName }}
          tar -xf ${{ inputs.uvmBlobName }}.tar -C ${{ inputs.uvmBlobName }}

      - name: Deploy VM
        run: |
          ./scripts/vm_create_traced.sh

      - name: Run containers on VM
        run: |
          ./scripts/tracing/trace_step.py --start 'Run containers on VM'
          cd workloads/workload-sidecar-with-fragments
          mkdir tmp
          cd tmp
          mv ../lcows_fragment.tar.gz ./
          cp ../vm-run-fragment-tests.ps1 ./
          c-aci-testing vm cp_into --deployment-name $DEPLOYMENT_NAME . 'C:\' 'C:\vm-run-fragment-tests.ps1 *> C:\fragment_tests.log'

      - name: Fetch output
        run: |
          ./scripts/tracing/trace_step.py --start 'Fetch output'
          c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME 'C:\fragment_tests.log' | tee fragment_tests.log

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Check dmesg
        if: always()
        run: |
          ./scripts/tracing/trace_step.py --start 'Check dmesg'
          c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'Get-Item C:\*\dmesg*.log | foreach { echo ""; echo ""; echo $_.FullName; cat -Raw $_ } > C:\all-dmesg.log'
          c-aci-testing vm cat --deployment-name $DEPLOYMENT_NAME 'C:\all-dmesg.log' > dmesg.log
          cat dmesg.log
          # will call trace --complete
          ./scripts/_check_dmesg.sh "dmesg.log"

      - name: Container output
        if: always()
        run: |
          ./scripts/vm_check_container_output.sh

      - name: 'Check run log contains "fragment: success"'
        run: |
          ./scripts/tracing/trace_step.py --start 'Check run log has success'
          err=""
          if grep -q "ERROR" fragment_tests.log; then
            err="Found ERROR in fragment_tests.log"
            echo $err
          elif ! grep -q "fragment: success" fragment_tests.log; then
            err="fragment_tests.log does not contain fragment: success"
            echo $err
          fi
          if [ -n "$err" ]; then
            ./scripts/tracing/trace_step.py --complete --err "$err"
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete --strict

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Remove VM
        if: always()
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vm remove --deployment-name $DEPLOYMENT_NAME
            # Don't leave VM hanging around even if deployment disappears
            az vm delete \
              --resource-group $RESOURCE_GROUP \
              --name ${DEPLOYMENT_NAME}-vm \
              --yes --force-deletion yes --verbose || true
          fi
