name: VN2 - Italy North

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '15 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vn2-italynorth.yml

jobs:
  vn2-italynorth:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: italynorth
      resource_group: vn2-aks-italynorth
      aks_cluster_name: vn2-aks-italynorth
