name: VN2 - Poland Central

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '26 19 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vn2-polandcentral.yml

jobs:
  vn2-polandcentral:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: polandcentral
      resource_group: c-aci-vn2
      aks_cluster_name: vn2-aks-polandcentral
