name: VN2 - UAE North

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '17 8 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vn2-uaenorth:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: uaenorth
      resource_group: vn2-aks-uaenorth
      aks_cluster_name: vn2-aks-uaenorth
