name: VN2 - Brazil South

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '42 17 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vn2-brazilsouth.yml

jobs:
  vn2-brazilsouth:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: brazilsouth
      resource_group: c-aci-vn2
      aks_cluster_name: vn2-aks-brazilsouth
