name: VN2 - West US

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '15 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vn2-westus.yml

jobs:
  vn2-westus:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: westus
      resource_group: vn2-aks-westus
      aks_cluster_name: vn2-aks-westus
