name: VN2 - West Europe

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '45 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vn2-westeurope:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: westeurope
      resource_group: c-aci-vn2
      aks_cluster_name: vn2-aks-westeurope
