name: VN2 - UK South

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '12 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vn2-uksouth:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: uksouth
      resource_group: vn2-aks-uksouth
      aks_cluster_name: vn2-aks-uksouth
