name: VN2 - Sweden Central

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '54 19 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vn2-swedencentral:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: swedencentral
      resource_group: c-aci-vn2
      aks_cluster_name: vn2-aks-swedencentral
