name: VN2 - Southeast Asia

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vn2-southeastasia.yml

jobs:
  vn2-southeastasia:
    secrets: inherit
    uses: ./.github/workflows/vn2-helloworld.yml
    with:
      location: southeastasia
      resource_group: vn2-aks-southeastasia
      aks_cluster_name: vn2-aks-southeastasia
