name: VN2 - New Zealand North

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '10 19 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vn2-newzealandnorth.yml

jobs:
  vn2-newzealandnorth:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: newzealandnorth
      resource_group: c-aci-vn2
      aks_cluster_name: vn2-aks-newzealandnorth
