name: VN2 - West US 2

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '53 21 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vn2-westus2:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: westus2
      resource_group: c-aci-vn2
      aks_cluster_name: vn2-aks-westus2
