name: VN2 - Region

# Due to permission issues we can only use pre-created AKSes, and we have one
# per region.
concurrency:
  group: vn2-aks-${{ inputs.location || 'northeurope' }}
  cancel-in-progress: false

permissions:
   id-token: write
   contents: read

on:
  pull_request:
    paths:
      - .github/workflows/vn2-region.yml
      - scripts/init_run.sh
      - workloads/vn2/**
      - workloads/volume/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/vn2-region.yml
      - scripts/init_run.sh
      - workloads/vn2/**
      - workloads/volume/**
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      resource_group:
        required: true
        type: string
      aks_cluster_name:
        required: true
        type: string
      cleanup:
        type: boolean
        description: Whether to cleanup the pods after testing
        default: true
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      resource_group:
        required: true
        type: string
      aks_cluster_name:
        required: true
        type: string
      cleanup:
        type: boolean
        description: Whether to cleanup the pods after testing
        default: true

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: vn2
  TEST_NAME: VN2 - Region
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'vn2' }}-${{ inputs.location }}-${{ github.run_number }}
  AKS_RESOURCE_GROUP: ${{ inputs.resource_group || 'c-aci-vn2' }}
  LOCATION: ${{ inputs.location || 'northeurope' }}
  AKS_CLUSTER_NAME: ${{ inputs.aks_cluster_name || 'vn2-aks-northeurope' }}
  CLEANUP: ${{ inputs.cleanup || 'true' }}
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'northeurope' }}
  ACI_EXPECTED_KERNEL_DATE: ${{ vars.ACI_EXPECTED_KERNEL_DATE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Environment
        id: environment
        run: ./scripts/load_environment.sh "${{ inputs.environment || 'cacitesting.env' }}" AKS_RESOURCE_GROUP AKS_CLUSTER_NAME

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      # Note: GitHub Actions runner images have Kubectl and Helm pre-installed.

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Start the AKS
        run: |
          # do nothing if AKS is already running
          if [ "$(az aks show --name $AKS_CLUSTER_NAME --resource-group $AKS_RESOURCE_GROUP --query 'powerState.code' -o tsv)" != "Running" ]; then
            echo "Starting AKS cluster..."
            az aks start --name $AKS_CLUSTER_NAME --resource-group $AKS_RESOURCE_GROUP
          fi

      - name: Delete any existing deployments and uninstall VN2
        run: |
          ./scripts/tracing/trace_step.py --start 'Delete any existing deployments and uninstall VN2'
          ./workloads/vn2/cleanup-vn2-helm.sh $AKS_RESOURCE_GROUP $AKS_CLUSTER_NAME
          # Waits a bit for the helm uninstall to really finish
          sleep 30

      - name: Deploy VN2 Helm Chart
        id: vn2_deploy
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy VN2 Helm Chart'
          ./workloads/vn2/deploy-vn2-helm.sh $AKS_RESOURCE_GROUP $AKS_CLUSTER_NAME
          echo "VN2_READY=1" >> $GITHUB_ENV
          helm list

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: 'Test case - info'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: info
          STEP_PREFIX: info
          REPOSITORY: prebuilt-test-containers
          TAG: latest
        run: |
          set -ex
          MONITOR_SECS=60 ./workloads/vn2/vn2-test-run.sh workloads/info
          echo "Parse container output"
          ./scripts/parse_container_output.py --fail-on-error output.log
          echo "Check info log has success"
          ./scripts/tracing/trace_step.py --start 'Check info log has success'
          ok=1
          grep -q "info: success" output.log || ok=0
          if [ $ok -ne 1 ]; then
            ./scripts/tracing/trace_step.py --complete --err 'info log does not contain success'
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete --strict

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - ccf_verify_uvm'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          # pod names can't contain '_'
          DEPLOYMENT_NAME: ccf-verify-uvm
          STEP_PREFIX: ccf_verify_uvm
          REPOSITORY: prebuilt-test-containers
          TAG: "latest"
        run: |
          set -ex
          MONITOR_SECS=60 ./workloads/vn2/vn2-test-run.sh workloads/ccf_verify_uvm
          echo "Parse container output"
          ./scripts/parse_container_output.py --fail-on-error output.log
          echo "Check ccf_verify_uvm log has success"
          ./scripts/tracing/trace_step.py --start 'Check ccf_verify_uvm log has success'
          ok=1
          grep -q "ccf_verify_uvm: success" output.log || ok=0
          if [ $ok -ne 1 ]; then
            ./scripts/tracing/trace_step.py --complete --err 'ccf_verify_uvm log does not contain success'
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete --strict

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - sample-pod.yaml'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: sample-pod
          STEP_PREFIX: sample-pod
        run: |
          cd workloads/vn2
          ./vn2-test-single-yaml-deploy.sh sample-pod.yaml
          status=$?
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vn2 remove --deployment-name sample-pod
          fi
          exit $status

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - stress test (4cpu, 16gb)'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          CPU: 4
          MEMORY_IN_GB: 16
          DEPLOYMENT_NAME: stress-4cpu-16gb
          REPOSITORY: prebuilt-test-containers/stress-tests-server-alpine
          TAG: latest
          POLICY_TYPE: debug
          STEP_PREFIX: stress-4cpu-16gb
        run: |
          ./workloads/vn2/stress_test.sh

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - stress test (18cpu, 64gb)'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' && contains(vars.VN2_BIG_CONTAINERS_REGIONS, format(',{0},', inputs.location)) }}
        env:
          CPU: 18
          MEMORY_IN_GB: 64
          DEPLOYMENT_NAME: stress-18cpu-64gb
          REPOSITORY: prebuilt-test-containers/stress-tests-server-alpine
          TAG: latest
          POLICY_TYPE: debug
          STEP_PREFIX: stress-18cpu-64gb
        run: |
          ./workloads/vn2/stress_test.sh

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - managed identity'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: managed-identity
          STEP_PREFIX: managed-identity
          REPOSITORY: ubuntu-with-curl
          TAG: "24.04"
        run: |
          set -exo pipefail

          # Managed identity lives in the dashboard resource group
          WAIT_FOR_OUTPUT=true ./workloads/vn2/vn2-test-run.sh workloads/managed_identity
          ./scripts/parse_container_output.py --must-have-output --fail-on-error output.log

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - thim'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: thim
          STEP_PREFIX: thim
          TAG: "2.14"
        run: |
          set -ex
          MONITOR_SECS=60 ./workloads/vn2/vn2-test-run.sh workloads/thim
          ./scripts/tracing/trace_step.py --start 'Check for errors'
          if grep -q 'ERROR' output.log; then
            echo "Error found in container log"
            ./scripts/tracing/trace_step.py --complete --err 'Error found in container log'
            exit 1
          fi
          if ! grep -q 'Doing repeat check' output.log; then
            echo "Incomplete container log"
            ./scripts/tracing/trace_step.py --complete --err 'Incomplete container log'
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - skr'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: skr
          STEP_PREFIX: skr
          VN2_MODE: "true"
          TAG: "2.14"
          POLICY_TYPE: generated
          ATTESTATION_ENDPOINT: ${{ vars.ATTESTATION_ENDPOINT }}
          HSM_ENDPOINT: ${{ vars.HSM_ENDPOINT_ACI }}
        run: |
          set -ex
          ./scripts/tracing/trace_step.py --start 'Test SKR'

          # Managed identity lives in the dashboard resource group
          # This is used as the key name - attempt to make it unique and
          # identifiable
          export DEPLOYMENT_NAME=vn2-${{ inputs.location || 'region' }}-skr-${{ github.run_number }}

          set +e -o pipefail
          python -m unittest discover -s workloads/skr 2>&1 | tee skr_test.log
          status=$?
          if [ $status -ne 0 ]; then
            echo "SKR test failed"
            maybe_err=(--err "SKR test failed")
          else
            maybe_err=()
          fi
          jq -Rs '{skrTestLog: .}' < skr_test.log | \
            ./scripts/tracing/trace_step.py --complete "${maybe_err[@]}" --output-from-stdin || exit 1
          exit $status

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - volume (vn2)'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: volume-vn2
          STEP_PREFIX: volume-vn2
        run: |
          ./workloads/vn2/run-volumes-test.sh workloads/volume/volume.yaml volumes-stress-test-vn2

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - volume (non-vn2)'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: volume-nonvn2
          STEP_PREFIX: volume-nonvn2
        run: |
          ./workloads/vn2/run-volumes-test.sh workloads/volume/volume-nonvn2.yaml volumes-stress-test-nonvn2

      - name: Re-log into Azure
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: 'Test case - net-liveness'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: net-liveness
          STEP_PREFIX: net-liveness
          REPOSITORY: prebuilt-test-containers
          TAG: tingmao.20260402
          CONTAINER_GROUP_COUNT: "2"
          MONITOR_SECS: "600"
          POLICY_TYPE: allow_all
        run: |
          ./workloads/vn2/net_liveness.sh

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Download vn2 logs
        if: always()
        continue-on-error: true
        run: |
          ./scripts/tracing/trace_step.py --start 'Download vn2 logs'
          kubectl logs pod/vn2-virtualnode-0 -n vn2 | gzip > vn2.log.gz
          ls -lh vn2.log.gz
          ./scripts/tracing/trace_step.py --start 'Upload vn2 logs as artifact'

      - name: Upload vn2 logs as artifact
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: vn2.log.gz
          path: vn2.log.gz

      - name: Report result
        if: always()
        continue-on-error: true
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Clean up VN2 Helm installation
        run: |
          if [ "$CLEANUP" != false ]; then
            ./workloads/vn2/cleanup-vn2-helm.sh $AKS_RESOURCE_GROUP $AKS_CLUSTER_NAME
          fi

      # Attempt to upgrade the AKS cluster, but don't fail this workflow if it fails
      # Only do this if we haven't got any errors (implied by no `if`) and also we want to do cleanup
      - name: Upgrade AKS
        continue-on-error: true
        run: |
          if [ "$CLEANUP" != false ]; then
            ./workloads/vn2/upgrade-aks.sh $AKS_RESOURCE_GROUP $AKS_CLUSTER_NAME
          fi

      # Also don't fail this workflow if stopping the AKS fails
      # Only do this if we haven't got any errors (implied by no `if`) and also we want to do cleanup
      - name: Stop AKS
        continue-on-error: true
        if: success() && inputs.location != 'australiacentral2'
        run: |
          if [ "$CLEANUP" != false ]; then
            az aks stop --name $AKS_CLUSTER_NAME --resource-group $AKS_RESOURCE_GROUP
          fi
