name: VN2 - Region

# Due to permission issues we can only use pre-created AKSes, and we have one
# per region.
concurrency:
  group: vn2-aks-${{ inputs.location || 'northeurope' }}
  cancel-in-progress: false

permissions:
   id-token: write
   contents: read

on:
  pull_request:
    paths:
      - .github/workflows/vn2-helloworld.yml
      - scripts/init_run.sh
      - workloads/vn2/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/vn2-helloworld.yml
      - scripts/init_run.sh
      - workloads/vn2/**
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      resource_group:
        required: true
        type: string
      aks_cluster_name:
        required: true
        type: string
      cleanup:
        type: boolean
        description: Whether to cleanup the pods after testing
        default: true
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      resource_group:
        required: true
        type: string
      aks_cluster_name:
        required: true
        type: string
      cleanup:
        type: boolean
        description: Whether to cleanup the pods after testing
        default: true

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: vn2
  TEST_NAME: VN2 - Region
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'vn2' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: ${{ inputs.resource_group || 'vn2-aks-northeurope' }}
  LOCATION: ${{ inputs.location || 'northeurope' }}
  AKS_CLUSTER_NAME: ${{ inputs.aks_cluster_name || 'vn2-aks-northeurope' }}
  CLEANUP: ${{ inputs.cleanup || 'true' }}
  MANAGED_IDENTITY: cacidashboard
  ACI_EXPECTED_KERNEL_DATE: ${{ vars.ACI_EXPECTED_KERNEL_DATE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      # Note: GitHub Actions runner images have Kubectl and Helm pre-installed.

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Start the AKS
        run: |
          # do nothing if AKS is already running
          if [ "$(az aks show --name $AKS_CLUSTER_NAME --resource-group $RESOURCE_GROUP --query 'powerState.code' -o tsv)" != "Running" ]; then
            echo "Starting AKS cluster..."
            az aks start --name $AKS_CLUSTER_NAME --resource-group $RESOURCE_GROUP
          fi

      - name: Delete any existing deployments and uninstall VN2
        run: |
          ./scripts/tracing/trace_step.py --start 'Delete any existing deployments and uninstall VN2'
          ./workloads/vn2/cleanup-vn2-helm.sh $RESOURCE_GROUP $AKS_CLUSTER_NAME
          # Waits a bit for the helm uninstall to really finish
          sleep 30

      - name: Deploy VN2 Helm Chart
        id: vn2_deploy
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy VN2 Helm Chart'
          ./workloads/vn2/deploy-vn2-helm.sh $RESOURCE_GROUP $AKS_CLUSTER_NAME
          echo "VN2_READY=1" >> $GITHUB_ENV

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: 'Test case - sample-pod.yaml'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          DEPLOYMENT_NAME: sample-pod
          STEP_PREFIX: sample-pod
        run: |
          set +ex
          cd workloads/vn2
          ./vn2-test-single-yaml-deploy.sh sample-pod.yaml
          status=$?
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vn2 remove --deployment-name sample-pod
          fi
          exit $status

      - name: 'Test case - stress test (4cpu, 16gb)'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' }}
        env:
          CPU: 4
          MEMORY_IN_GB: 16
          DEPLOYMENT_NAME: stress-4cpu-16gb
          REGISTRY: ghcr.io
          REPOSITORY: ${{ github.repository }}/test-containers/stress-tests-server-alpine
          TAG: latest
          POLICY_TYPE: debug
          STEP_PREFIX: stress-4cpu-16gb
        run: |
          ./workloads/vn2/stress_test.sh

      - name: 'Test case - stress test (18cpu, 64gb)'
        if: ${{ !cancelled() && steps.vn2_deploy.outcome == 'success' && (inputs.location == 'eastus2euap') }}
        env:
          CPU: 18
          MEMORY_IN_GB: 64
          DEPLOYMENT_NAME: stress-18cpu-64gb
          REGISTRY: ghcr.io
          REPOSITORY: ${{ github.repository }}/test-containers/stress-tests-server-alpine
          TAG: latest
          POLICY_TYPE: debug
          STEP_PREFIX: stress-18cpu-64gb
        run: |
          ./workloads/vn2/stress_test.sh

      - name: Clean up VN2 Helm installation
        run: |
          if [ "$CLEANUP" != false ]; then
            ./workloads/vn2/cleanup-vn2-helm.sh $RESOURCE_GROUP $AKS_CLUSTER_NAME
          fi

      # Attempt to upgrade the AKS cluster, but don't fail this workflow if it fails
      # Only do this if we haven't got any errors (implied by no `if`) and also we want to do cleanup
      - name: Upgrade AKS
        continue-on-error: true
        run: |
          if [ "$CLEANUP" != false ]; then
            ./workloads/vn2/upgrade-aks.sh $RESOURCE_GROUP $AKS_CLUSTER_NAME
          fi

      # Also don't fail this workflow if stopping the AKS fails
      # Only do this if we haven't got any errors (implied by no `if`) and also we want to do cleanup
      - name: Stop AKS
        continue-on-error: true
        run: |
          if [ "$CLEANUP" != false ]; then
            az aks stop --name $AKS_CLUSTER_NAME --resource-group $RESOURCE_GROUP
          fi
