name: VN2 - Germany West Central

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '5 7 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vn2-germanywestcentral:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: germanywestcentral
      resource_group: vn2-aks-germanywestcentral
      aks_cluster_name: vn2-aks-germanywestcentral
