name: VN2 - Switzerland North

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/vn2-switzerlandnorth.yml

jobs:
  vn2-switzerlandnorth:
    secrets: inherit
    uses: ./.github/workflows/vn2-helloworld.yml
    with:
      location: switzerlandnorth
      resource_group: vn2-aks-switzerlandnorth
      aks_cluster_name: vn2-aks-switzerlandnorth
