name: VN2 - East US 2 EUAP

permissions:
   id-token: write
   contents: read

on:
  schedule:
    - cron: '17 21 * * *'  # managed by scripts/spread_out_schedules.py
  workflow_dispatch:

jobs:
  vn2-eastus2euap:
    secrets: inherit
    uses: ./.github/workflows/vn2-region.yml
    with:
      location: eastus2euap
      resource_group: c-aci-vn2
      aks_cluster_name: vn2-aks-eastus2euap
