name: Workload - Managed Identity

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - workloads/managed_identity/**
      - .github/workflows/workload-managed-identity.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - workloads/managed_identity/**
      - .github/workflows/workload-managed-identity.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      use_vnet:
        type: boolean
        description: Whether to use a virtual network for the container group
        default: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 1
      cleanup:
        type: choice
        description: "Whether to cleanup the container group after testing (true/false/always)"
        default: "true"
        options:
          - "true"
          - "false"
          - "always"
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      is_big_containers_test:
        type: boolean
        default: false
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      use_vnet:
        type: boolean
        description: Whether to use a virtual network for the container group
        default: false
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 1
      cleanup:
        type: string
        description: "Whether to cleanup the container group after testing (true/false/always)"
        default: "true"
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''
      is_big_containers_test:
        type: boolean
        default: false

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: ${{ inputs.is_big_containers_test && 'aci-next' || 'aci' }}
  TEST_NAME: ${{ inputs.is_big_containers_test && 'Managed Identity (BigContainers)' || 'Managed Identity' }}
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'managed-identity' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION_ACI }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboardaci.azurecr.io
  REPOSITORY: ubuntu-with-curl
  TAG: "24.04"
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'westeurope' }}
  LOCATION: ${{ inputs.location || 'westeurope' }}
  USE_VNET: ${{ inputs.use_vnet || false }}
  CPU: ${{ inputs.cpu || 1 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 1 }}
  CLEANUP: ${{ inputs.cleanup }}
  POLICY_TYPE: ${{ inputs.policy_type || 'generated' }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}
  RUN_FEATURES: managed_identity${{ inputs.use_vnet && ',vnet' || '' }}${{ inputs.is_big_containers_test && ',big_containers' || '' }}

jobs:
  managed-identity:
    name: ${{ inputs.id || 'managed-identity' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ACI }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        if: ${{ env.POLICY_TYPE != 'allow_all' }}
        run: c-aci-testing images pull workloads/managed_identity

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/managed_identity --parameter useVnet=$USE_VNET
          c-aci-testing aci param_set workloads/managed_identity --parameter cpu=$CPU
          c-aci-testing aci param_set workloads/managed_identity --parameter memoryInGb=$MEMORY_IN_GB

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/managed_identity --deployment-name $DEPLOYMENT_NAME
          cat workloads/managed_identity/policy_managed_identity.rego

      - name: Deploy Container Group
        run: |
          ./scripts/aci_deploy_traced.sh workloads/managed_identity

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Monitor Container Group
        if: always()
        continue-on-error: true
        run: |
          set -eo pipefail
          ./scripts/tracing/trace_step.py --start 'Monitor Container Group'
          time=0
          while [ $time -lt 10 ]; do
            sleep 15 # waits for curl test to finish
            c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME | tee output.log
            if grep -q 'OUTPUT: ' output.log; then
              break
            fi
            time=$((time + 1))
          done

      - name: Parse output
        if: always()
        run: |
          ./scripts/parse_container_output.py --must-have-output --fail-on-error output.log

      - name: Get Container States
        if: always()
        continue-on-error: true
        run: |
          sleep 60 # Ensure all states are up to date
          ./scripts/trace_container_states.sh

      - name: Remove Container Group
        if: (inputs.cleanup != 'false' && success()) || inputs.cleanup == 'always'
        run: |
          c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME

      - name: Be extra sure we removed the containers
        if: (inputs.cleanup != 'false' && success()) || inputs.cleanup == 'always'
        run: |
          set +e
          az container delete --name $DEPLOYMENT_NAME --resource-group $RESOURCE_GROUP --yes
