name: Workload - Secrets

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - workloads/secrets/**
      - .github/workflows/workload-secrets.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - workloads/secrets/**
      - .github/workflows/workload-secrets.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: aci
  TEST_NAME: Secrets
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'secrets' }}-${{ inputs.location }}-${{ github.run_number }}
  REGISTRY: mcr.microsoft.com
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'westeurope' }}
  LOCATION: ${{ inputs.location || 'westeurope' }}
  CLEANUP: ${{ inputs.cleanup }}
  POLICY_TYPE: ${{ inputs.policy_type || 'generated' }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}
  TAG: '3.0'
  RUN_FEATURES: secrets

jobs:
  secrets:
    name: ${{ inputs.id || 'secrets' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Environment
        id: environment
        run: ./scripts/load_environment.sh "${{ inputs.environment || 'cacitesting.env' }}" REGISTRY

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        if: ${{ env.POLICY_TYPE != 'allow_all' }}
        run: c-aci-testing images pull workloads/secrets

      - name: Generate Secret
        run: |
          secret=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 20)
          secret_b64=$(echo -n "$secret" | base64 -w0)
          {
            echo "SECRET_RAW=$secret"
            echo "SECRET_B64=$secret_b64"
          } >> $GITHUB_ENV

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/secrets --parameter "mysecret='$SECRET_B64'"

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/secrets --deployment-name $DEPLOYMENT_NAME
          cat workloads/secrets/policy_secrets.rego

      - name: Deploy Container Group
        run: |
          ./scripts/aci_deploy_traced.sh workloads/secrets

      - name: Monitor Container Group
        run: |
          sleep 20
          ./scripts/tracing/trace_step.py --start 'Monitor Container Group'
          c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME | tee output.log

      - name: Find secret in output
        run: |
          ./scripts/tracing/trace_step.py --start 'Find secret in output'
          found=false
          grep -Fq "$SECRET_RAW" output.log && found=true
          if [[ $found == true ]]; then
            echo "Secret found in output"
            ./scripts/tracing/trace_step.py --complete --strict
          else
            echo "Secret not found in output"
            ./scripts/tracing/trace_step.py --complete --strict --err 'Secret not found in output'
          fi

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Get Container States
        if: always()
        continue-on-error: true
        run: |
          ./scripts/trace_container_states.sh

      - name: Remove Container Group
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME
          fi
