name: Workload - Stress Tests

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - workloads/stress_tests/**
      - .github/workflows/workload-stress-tests.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - workloads/stress_tests/**
      - .github/workflows/workload-stress-tests.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The total number of CPU cores
        default: 4
      memory_in_gb:
        type: number
        description: The total amount of memory in GB
        default: 4
      cleanup:
        type: choice
        description: "Whether to cleanup the container group after testing (true/false/always)"
        default: "true"
        options:
          - "true"
          - "false"
          - "always"
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      script:
        type: choice
        description: The script to run
        default: workload_fio
        options:
          - workload_attestation_loop
          - workload_check_threads
          - workload_cpu
          - workload_cpu_fio
          - workload_exec
          - workload_fio
          - workload_multicpu_fio
          - workload_tar
      is_big_containers_test:
        type: boolean
        default: false
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The total number of CPU cores
        default: 4
      memory_in_gb:
        type: number
        description: The total amount of memory in GB
        default: 4
      cleanup:
        type: string
        description: "Whether to cleanup the container group after testing (true/false/always)"
        default: "true"
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      script:
        type: string
        description: The script to run
        default: workload_fio
      is_big_containers_test:
        type: boolean
        default: false
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: ${{ inputs.is_big_containers_test && 'aci-next' || 'aci' }}
  TEST_NAME: ${{ inputs.is_big_containers_test && 'Stress Tests (BigContainers)' || 'Stress Tests' }}
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'stress' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}/test-containers/stress-tests-server-alpine
  TAG: latest
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'westus' }}
  LOCATION: ${{ inputs.location || 'westus' }}
  CPU: ${{ inputs.cpu || 4 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 4 }}
  CLEANUP: ${{ inputs.cleanup }}
  POLICY_TYPE: ${{ inputs.policy_type || 'generated' }}
  SCRIPT: ${{ inputs.script || 'workload_fio' }}
  ACI_EXPECTED_KERNEL_DATE: ${{ vars.ACI_EXPECTED_KERNEL_DATE }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}
  RUN_FEATURES: 'public_ip'

jobs:
  stress-tests:
    name: ${{ inputs.id || 'stress-tests' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        if: ${{ env.POLICY_TYPE != 'allow_all' }}
        run: c-aci-testing images pull workloads/stress_tests

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/stress_tests --parameter totalCpus=$CPU
          c-aci-testing aci param_set workloads/stress_tests --parameter totalMemoryGB=$MEMORY_IN_GB
          c-aci-testing aci param_set workloads/stress_tests --parameter "script='$SCRIPT'"
          echo stress_tests.bicepparam:
          cat workloads/stress_tests/stress_tests.bicepparam

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/stress_tests --deployment-name $DEPLOYMENT_NAME
          cat workloads/stress_tests/policy_stress_tests.rego

      - name: Deploy Container Group
        run: |
          ./scripts/aci_deploy_traced.sh workloads/stress_tests

      - name: Wait for IP address
        run: |
          ./scripts/aci_get_ip.sh

      - name: Curl Server
        run: |
          ./scripts/curl_check_with_retry.sh "http://$ip_address:80"

      - name: Let container run for 1min and test again
        run: |
          sleep 100
          ./scripts/tracing/trace_step.py --start 'Curl Server after 1min'
          timeout -s INT 1m curl --fail-with-body http://$ip_address:80 || exit 1

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Monitor Container Group
        if: always()
        continue-on-error: true
        run: |
          set -eo pipefail
          ./scripts/tracing/trace_step.py --start 'Monitor Container Group'
          rm -f output.log
          c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME | tee output.log

      - name: Parse output
        if: always()
        run: |
          ./scripts/parse_container_output.py --fail-on-error --error-count-threshold 15 output.log

      - name: Check correct kernel version
        run: scripts/check_uname_in_output.sh output.log

      - name: Get Container States
        if: always()
        continue-on-error: true
        run: |
          ./scripts/trace_container_states.sh

      - name: Check dmesg
        if: always()
        run: |
            ./scripts/tracing/trace_step.py --start 'Check dmesg'
            dmesg_file="dmesg.log"

            timeout -s INT 1m curl --fail-with-body http://$ip_address:80/dmesg.log -o $dmesg_file
            if [ $? -ne 0 ]; then
              echo "Failed to get dmesg:"
              cat $dmesg_file
              exit 1
            fi

            # will call trace --complete
            ./scripts/_check_dmesg.sh "$dmesg_file"

      - name: Remove Container Group
        if: (inputs.cleanup != 'false' && success()) || inputs.cleanup == 'always'
        run: |
          c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME

      - name: Be extra sure we removed the containers
        if: (inputs.cleanup != 'false' && success()) || inputs.cleanup == 'always'
        run: |
          set +e
          az container delete --name $DEPLOYMENT_NAME --resource-group $RESOURCE_GROUP --yes
