name: Regular VM Perf

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/workload-perf-regular-vm.yml
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - .github/workflows/workload-perf-regular-vm.yml
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_D8as_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_D8as_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true

env:
  DEPLOYMENT_NAME: ${{ inputs.id || 'perf-regular-vm' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  # MANAGED_IDENTITY: cacidashboard
  # STORAGE_ACCOUNT: cacitestingstorage
  LOCATION: ${{ inputs.location || 'uaenorth' }}
  CLEANUP: ${{ inputs.cleanup }}
  VM_SIZE: ${{ inputs.vmSize || 'Standard_D8as_v5' }}

jobs:
  perf-regular-vm:
    name: ${{ inputs.id || 'perf-regular-vm' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Deploy VM
        run: |
          cd workloads/perf-regular-vm
          PASSWORD=$(head --bytes 8 /dev/urandom | base64)
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --name $DEPLOYMENT_NAME \
            --template-file vm.bicep \
            --parameters \
              "location=westeurope" \
              "deploymentName=$DEPLOYMENT_NAME" \
              "adminPassword=$PASSWORD" \
              "vmSize=$VM_SIZE"

      - name: Check run log
        if: always()
        run: |
          az vm run-command invoke \
          --resource-group $RESOURCE_GROUP \
          --name ${DEPLOYMENT_NAME}-vm \
          --command-id RunShellScript \
          --scripts "cat /tmp/perf.log" |\
            jq -r '.value[].message'

      - name: Remove VM
        run: |
          if [ "$CLEANUP" != false ]; then
            az vm delete \
              --resource-group $RESOURCE_GROUP \
              --name ${DEPLOYMENT_NAME}-vm \
              --yes --force-deletion yes --verbose
            az network vnet delete \
              --resource-group $RESOURCE_GROUP \
              --name ${DEPLOYMENT_NAME}-vnet --verbose
          fi
