name: Workload - Stress Tests (No server)

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - workloads/stress_tests_noserver/**
      - .github/workflows/workload-stress-tests-noserver.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - workloads/stress_tests_noserver/**
      - .github/workflows/workload-stress-tests-noserver.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The total number of CPU cores
        default: 4
      memory_in_gb:
        type: number
        description: The total amount of memory in GB
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: choice
        description: The type of policy to use
        default: allow_all
        options:
          - generated
          - debug
          - allow_all
      script:
        type: choice
        description: The script to run
        default: workload_fio
        options:
          - workload_attestation_loop
          - workload_check_threads
          - workload_cpu
          - workload_cpu_fio
          - workload_exec
          - workload_fio
          - workload_multicpu_fio
          - workload_tar
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The total number of CPU cores
        default: 4
      memory_in_gb:
        type: number
        description: The total amount of memory in GB
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: allow_all
      script:
        type: string
        description: The script to run
        default: workload_fio
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: aci
  TEST_NAME: Stress Tests (No server)
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'stress-nosrv' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION_ACI }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboardaci.azurecr.io
  REPOSITORY: prebuilt-test-containers/stress-tests-noserver-alpine
  TAG: latest
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'westus' }}
  LOCATION: ${{ inputs.location || 'westus' }}
  CPU: ${{ inputs.cpu || 4 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 4 }}
  CLEANUP: ${{ inputs.cleanup }}
  POLICY_TYPE: ${{ inputs.policy_type || 'allow_all' }}
  SCRIPT: ${{ inputs.script || 'workload_fio' }}
  ACI_EXPECTED_KERNEL_DATE: ${{ vars.ACI_EXPECTED_KERNEL_DATE }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}
  RUN_FEATURES: ''

jobs:
  stress-tests-noserver:
    name: ${{ inputs.id || 'stress-tests-noserver' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ACI }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        if: ${{ env.POLICY_TYPE != 'allow_all' }}
        run: c-aci-testing images pull workloads/stress_tests_noserver

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/stress_tests_noserver --parameter totalCpus=$CPU
          c-aci-testing aci param_set workloads/stress_tests_noserver --parameter totalMemoryGB=$MEMORY_IN_GB
          c-aci-testing aci param_set workloads/stress_tests_noserver --parameter "script='$SCRIPT'"
          echo stress_tests.bicepparam:
          cat workloads/stress_tests_noserver/stress_tests.bicepparam

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/stress_tests_noserver --deployment-name $DEPLOYMENT_NAME
          cat workloads/stress_tests_noserver/policy_stress_tests.rego

      - name: Deploy Container Group
        run: |
          ./scripts/aci_deploy_traced.sh workloads/stress_tests_noserver

      - name: Let container run for some time
        run: sleep 100

      - name: Monitor Container Group
        run: |
          set -eo pipefail
          ./scripts/tracing/trace_step.py --start 'Monitor Container Group'
          rm -f output.log
          c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME | tee output.log

      - name: Parse output
        if: always()
        run: |
          ./scripts/parse_container_output.py --fail-on-error --error-count-threshold 15 output.log

      - name: Check correct kernel version
        run: scripts/check_uname_in_output.sh output.log

      - name: Check output and dmesg
        run: |
          ./scripts/tracing/trace_step.py --start 'Check Output and dmesg'

          grep -q -F 'Stress test container alive' output.log || no_alive_output=true
          if [ -n "$no_alive_output" ]; then
            echo "No 'Stress test container alive' message found in output.log"
            exit 1
          fi
          dmesg_file="output.log"

          # will call trace --complete
          ./scripts/_check_dmesg.sh "$dmesg_file"

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Get Container States
        if: always()
        continue-on-error: true
        run: |
          ./scripts/trace_container_states.sh

      - name: Remove Container Group
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME
          fi
