name: Workload - Server

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - workloads/server/**
      - .github/workflows/workload-server.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - workloads/server/**
      - .github/workflows/workload-server.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 2
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 2
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: aci
  TEST_NAME: Server
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'server' }}-${{ inputs.location }}-${{ github.run_number }}
  REPOSITORY: prebuilt-test-containers
  TAG: latest
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'westeurope' }}
  LOCATION: ${{ inputs.location || 'westeurope' }}
  CPU: ${{ inputs.cpu || 2 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 4 }}
  CLEANUP: ${{ inputs.cleanup }}
  POLICY_TYPE: ${{ inputs.policy_type || 'generated' }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}
  RUN_FEATURES: 'public_ip'

jobs:
  server:
    name: ${{ inputs.id || 'server' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Environment
        id: environment
        run: ./scripts/load_environment.sh "${{ inputs.environment || 'cacitesting.env' }}"

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        if: ${{ env.POLICY_TYPE != 'allow_all' }}
        run: c-aci-testing images pull workloads/server

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/server --parameter cpu=$CPU
          c-aci-testing aci param_set workloads/server --parameter memoryInGb=$MEMORY_IN_GB

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/server --deployment-name $DEPLOYMENT_NAME
          cat workloads/server/policy_server.rego

      - name: Deploy Container Group
        run: |
          ./scripts/aci_deploy_traced.sh workloads/server

      - name: Wait for IP address
        run: |
          ./scripts/aci_get_ip.sh

      - name: Curl Server
        run: |
          ./scripts/curl_check_with_retry.sh "http://$ip_address:80"

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      # See container output even if curl check from our end fails
      - name: Monitor Container Group
        if: always()
        run: |
          set -eo pipefail
          sleep 210 # waits for anything inside the container to finish
          ./scripts/tracing/trace_step.py --start 'Monitor Container Group'
          c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME | tee output.log
          jq -Rs '{containerLog: .}' output.log | ./scripts/tracing/trace_step.py \
            --complete --strict --output-from-stdin

      - name: Parse output
        if: always()
        run: |
          ./scripts/parse_container_output.py --must-have-output --fail-on-error output.log

      - name: Get Container States
        if: always()
        continue-on-error: true
        run: |
          ./scripts/trace_container_states.sh

      - name: Remove Container Group
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME
          fi
