name: Workload - Server with Wait

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - workloads/server
      - .github/workflows/workload-server-with-wait.yml
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - workloads/server
      - .github/workflows/workload-server-with-wait.yml
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 2
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 2
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: aci
  TEST_NAME: Server with Wait
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'server-with-wait' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboard.azurecr.io
  MANAGED_IDENTITY: cacidashboard
  LOCATION: ${{ inputs.location || 'westeurope' }}
  CPU: ${{ inputs.cpu || 2 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 4 }}
  CLEANUP: ${{ inputs.cleanup }}
  POLICY_TYPE: ${{ inputs.policy_type || 'generated' }}
  TAG: "2.6"

jobs:
  server-with-wait:
    name: ${{ inputs.id || 'server-with-wait' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        run: c-aci-testing images pull workloads/server

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/server --parameter cpu=$CPU
          c-aci-testing aci param_set workloads/server --parameter memoryInGb=$MEMORY_IN_GB

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/server --deployment-name $DEPLOYMENT_NAME
          cat workloads/server/policy_server.rego

      - name: Deploy Container Group
        run: |
          ./scripts/tracing/trace_step.py --start 'Deploy Container Group'
          c-aci-testing aci deploy workloads/server --deployment-name $DEPLOYMENT_NAME

      - name: Curl Server
        run: |
          ./scripts/tracing/trace_step.py --start 'Wait for IP address'
          ip_address=""
          timeout=$(($(date +%s) + (60 * 10))) # 10 minutes
          while [[ -z "$ip_address" && $(date +%s) -lt $timeout ]]; do
            ip_address=$(c-aci-testing aci get ips --deployment-name $DEPLOYMENT_NAME | sed "s/\['\([^']*\)'\]/\1/")
            echo "IP Address: $ip_address"
            sleep 5
          done

          ./scripts/tracing/trace_step.py --start 'Curl Server'
          echo "Attempting to send a request..."
          timeout=$(($(date +%s) + (60 * 10))) # 10 minutes
          while [[ $(date +%s) -lt $timeout ]]; do
            curl http://$ip_address:80 --max-time 20 && exit 0
          done
          exit 1

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Monitor Container Group
        if: always()
        continue-on-error: true
        run: |
          echo "Attempting to get container logs..."
          timeout=$(($(date +%s) + (60 * 10))) # 10 minutes
          while [[ $(date +%s) -lt $timeout ]]; do
            c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME && exit 0
            sleep 20
          done
          exit 1


      - name: Get Container States
        if: always()
        continue-on-error: true
        run: |
          sleep 60 # Ensure all states are up to date
          ./scripts/trace_container_states.sh

      - name: Remove Container Group
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME
          fi
