name: Workload - Info

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - workloads/info/**
      - .github/workflows/workload-info.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
  push:
    paths:
      - workloads/info/**
      - .github/workflows/workload-info.yml
      - scripts/init_run.sh
      - scripts/install-c-aci-testing.sh
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The availability zone to deploy to
        default: ''
      use_vnet:
        type: boolean
        description: Whether to use a virtual network for the container group
        default: false
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 1
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      require_host_amd_cert:
        type: boolean
        description: Whether the workload should fail if /security-context-*/host-amd-cert-base64 is missing
        default: true
      expect_uvm_signature:
        type: string
        description: Which UVM endorsement DID to validate against ('Prod' or 'Test')
        default: Prod
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment file to load
        default: cacitesting.env
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      zone:
        type: string
        description: The availability zone to deploy to
        default: ''
      use_vnet:
        type: boolean
        description: Whether to use a virtual network for the container group
        default: false
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 1
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      policy_type:
        type: string
        description: The type of policy to use
        default: generated
      require_host_amd_cert:
        type: boolean
        description: Whether the workload should fail if /security-context-*/host-amd-cert-base64 is missing
        default: true
      expect_uvm_signature:
        type: string
        description: Which UVM endorsement DID to validate against ('Prod' or 'Test')
        default: Prod
      test_schedule:
        type: string
        description: Trace marker by scheduled runs only
        default: ''

env:
  KUSTO_CONNECTION_STRING: ${{ secrets.KUSTO_CONNECTION_STRING }}
  KUSTO_DATABASE: ${{ secrets.KUSTO_DATABASE }}
  KUSTO_TABLE: CACITestStepTrace
  TEST_TYPE: aci
  TEST_NAME: Info
  RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEPLOYMENT_NAME: ${{ inputs.id || 'info' }}-${{ inputs.location }}-${{ github.run_number }}
  REPOSITORY: prebuilt-test-containers
  TAG: latest
  MANAGED_IDENTITY: cacidashboard-${{ inputs.location || 'westeurope' }}
  LOCATION: ${{ inputs.location || 'westeurope' }}
  ZONE: ${{ inputs.zone }}
  USE_VNET: ${{ inputs.use_vnet || false }}
  CPU: ${{ inputs.cpu || 1 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 1 }}
  CLEANUP: ${{ inputs.cleanup }}
  POLICY_TYPE: ${{ inputs.policy_type || 'generated' }}
  REQUIRE_HOST_AMD_CERT: ${{ inputs.require_host_amd_cert != false && 'true' || 'false' }}
  EXPECT_UVM_SIGNATURE: ${{ inputs.expect_uvm_signature || 'Prod' }}
  TEST_SCHEDULE: ${{ inputs.test_schedule }}
  RUN_FEATURES: ${{ inputs.use_vnet && 'vnet' || '' }}

jobs:
  info:
    name: ${{ inputs.id || 'info' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Environment
        id: environment
        run: ./scripts/load_environment.sh "${{ inputs.environment || 'cacitesting.env' }}"

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ACI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ steps.environment.outputs.subscription }}

      - name: Initialize Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/init_run.sh

      - name: Pull Image
        if: ${{ env.POLICY_TYPE != 'allow_all' }}
        run: c-aci-testing images pull workloads/info

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/info --parameter "zone='$ZONE'"
          c-aci-testing aci param_set workloads/info --parameter useVnet=$USE_VNET
          c-aci-testing aci param_set workloads/info --parameter cpu=$CPU
          c-aci-testing aci param_set workloads/info --parameter memoryInGb=$MEMORY_IN_GB
          c-aci-testing aci param_set workloads/info --parameter requireHostAmdCert=$REQUIRE_HOST_AMD_CERT
          c-aci-testing aci param_set workloads/info --parameter "expectUvmSignature='$EXPECT_UVM_SIGNATURE'"

      - name: Generate Security Policy
        run: |
          ./scripts/tracing/trace_step.py --start 'Generate Policy'
          c-aci-testing policies gen workloads/info --deployment-name $DEPLOYMENT_NAME
          cat workloads/info/policy_info.rego

      - name: Deploy Container Group
        run: |
          ./scripts/aci_deploy_traced.sh workloads/info

      - name: Report result
        if: always()
        run: |
          ./scripts/trace_run_result.sh ${{ job.status }}

      - name: Monitor Container Group
        if: always()
        continue-on-error: true
        run: |
          set -eo pipefail
          ./scripts/tracing/trace_step.py --start 'Monitor Container Group'
          sleep 120
          c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME | tee output.log
          cat output.log | jq -R -s '{info: .}' | ./scripts/tracing/trace_step.py --complete --strict --output-from-stdin

      - name: Parse output
        run: |
          ./scripts/parse_container_output.py --fail-on-error output.log

      - name: 'Check info log contains "info: success"'
        run: |
          ./scripts/tracing/trace_step.py --start 'Check info log has success'
          ok=1
          grep -q "info: success" output.log || ok=0
          if [ $ok -ne 1 ]; then
            ./scripts/tracing/trace_step.py --complete --err 'info log does not contain success'
            exit 1
          fi
          ./scripts/tracing/trace_step.py --complete --strict

      - name: Get Container States
        if: always()
        continue-on-error: true
        run: |
          sleep 60 # Ensure all states are up to date
          ./scripts/trace_container_states.sh

      - name: Remove Container Group
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME
          fi
